[drive]
host = 'localhost'
port = 8081
target = 'integration_test/app_test.dart'
driver = 'test_driver/integration_test.dart'
packageName = 'pl.leancode.maestro.example'
bundleId = 'pl.leancode.maestro.Example'
