name: maestro
description: >
  Simple, easy-to-learn, Flutter-native UI Testing framework eliminating
  limitations of flutter-driver
version: 0.0.1
homepage: https://github.com/leancodepl/maestro

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.1
  http: ^0.13.4

dev_dependencies:
  leancode_lint: ^1.2.1

executables:
  maestro:
