//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.patrol_next.contracts;

@kotlin.jvm.JvmName("-initializegetNotificationsRequest")
inline fun getNotificationsRequest(block: pl.leancode.patrol_next.contracts.GetNotificationsRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol_next.contracts.Contracts.GetNotificationsRequest =
  pl.leancode.patrol_next.contracts.GetNotificationsRequestKt.Dsl._create(pl.leancode.patrol_next.contracts.Contracts.GetNotificationsRequest.newBuilder()).apply { block() }._build()
object GetNotificationsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.patrol_next.contracts.Contracts.GetNotificationsRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.patrol_next.contracts.Contracts.GetNotificationsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.patrol_next.contracts.Contracts.GetNotificationsRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.patrol_next.contracts.Contracts.GetNotificationsRequest.copy(block: pl.leancode.patrol_next.contracts.GetNotificationsRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol_next.contracts.Contracts.GetNotificationsRequest =
  pl.leancode.patrol_next.contracts.GetNotificationsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
