test_linux_task:
  name: Test `patrol develop` on Linux
  required_pr_labels: 
    - 'package: patrol_cli'
    - 'package: patrol'
    - 'cirrusci'
  container:
    image: ghcr.io/cirruslabs/flutter:stable
    cpu: 6
    memory: 10G
    kvm: 'true'
  env:
    PATH: $HOME/.pub-cache/bin:$HOME/fvm/default/bin:$CIRRUS_WORKING_DIR/fvm:${PATH}
    FLUTTER_VERSION: '3.16.0'
    EMULATOR_API_LEVEL: '34'
    EMULATOR_ABI: google_apis_playstore;x86_64
    EMULATOR_IMAGE: system-images;android-${EMULATOR_API_LEVEL};${EMULATOR_ABI}
  timeout_in: 30m

  set_up_fvm_script: |
    curl -LO https://github.com/fluttertools/fvm/releases/download/2.4.1/fvm-2.4.1-linux-x64.tar.gz
    tar -xf fvm-2.4.1-linux-x64.tar.gz
  setup_flutter_script: |
    echo "y" | fvm global $FLUTTER_VERSION
    fvm doctor
    flutter --version
    flutter precache --android
    cd packages/patrol/example && flutter build apk --config-only
  melos_bootstrap_script: |
    dart pub global activate melos
    melos bootstrap
  setup_patrol_cli_script:
    - dart pub global activate --source path packages/patrol_cli && patrol
  setup_emulator_script: |
    sdkmanager --install "$EMULATOR_IMAGE"
    sdkmanager --install emulator
  create_emulator_script: |
    avdmanager -s create avd -n MyAVD -k "$EMULATOR_IMAGE"
    cat << EOF >> ~/.android/avd/MyAVD.avd/config.ini
    hw.cpu.ncore=2
    hw.gpu.enabled=yes
    hw.gpu.mode=swiftshader_indirect
    hw.ramSize=3072
    disk.dataPartition.size=6G
    vm.heapSize=576
    hw.lcd.density=440
    hw.lcd.height=2220
    hw.lcd.width=1080
    EOF
  start_emulator_background_script:
    - $ANDROID_HOME/emulator/emulator @MyAVD -verbose -no-snapshot-save -no-window -noaudio -no-boot-anim -accel on
  wait_for_emulator_script:
    - android-wait-for-emulator
  generate_gradle_wrapper_script: |
    cd dev/e2e_app/lib
    flutter pub get
    flutter build apk --config-only
  patrol_develop_script: |
    cd dev/cli_tests
    dart pub get
    dart patrol_develop_test.dart

test_macos_task:
  name: Test `patrol develop` on macOS
  required_pr_labels: 
    - 'package: patrol_cli'
    - 'package: patrol'
    - 'cirrusci'
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-xcode:latest
  env:
    PATH: $HOME/.pub-cache/bin:$HOME/fvm/default/bin:${PATH}
    FLUTTER_VERSION: '3.16.0'
  timeout_in: 30m

  set_up_fvm_script: |
    brew tap leoafarias/fvm
    brew install fvm
  setup_flutter_script: |
    echo "y" | fvm global $FLUTTER_VERSION
    fvm doctor
    flutter --version
    flutter precache --ios
  melos_bootstrap_script: |
    dart pub global activate melos
    melos bootstrap
  setup_patrol_cli_script:
    - dart pub global activate --source path packages/patrol_cli && patrol
  setup_simulator_script: |
    xcrun simctl boot "iPhone 15 Pro Max"
  patrol_test_script: |
    cd dev/cli_tests
    dart pub get
    dart patrol_develop_test.dart
