test_android_task:
  name: Test `patrol develop` on Linux
  container:
    image: cirrusci/flutter:stable
    cpu: 8
    memory: 32G
    kvm: 'true'
  env:
    PATH: $HOME/.pub-cache/bin:${PATH}
    EMULATOR_API_LEVEL: '34'
    EMULATOR_ABI: google_apis_playstore;x86_64
    EMULATOR_IMAGE: system-images;android-${EMULATOR_API_LEVEL};${EMULATOR_ABI}
  timeout_in: 30m

  pub_cache:
    folder: ~/.pub-cache
  setup_flutter_script:
    - flutter precache
  generate_gradlew_script: |
    cd packages/patrol/example
    flutter build apk --target lib/main.dart --debug --flavor=does-not-exist &
    buildpid="$!"
    while [ ! -e "android/gradlew" ]; do
        echo "waiting for gradlew to generate..."
        sleep 2
    done
    kill $buildpid
  setup_patrol_cli_script:
    - dart pub global activate --source path packages/patrol_cli && patrol
  setup_emulator_script: |
    sdkmanager --install "$EMULATOR_IMAGE"
    sdkmanager --install emulator
  create_emulator_script: |
    avdmanager -s create avd -n MyAVD -k "$EMULATOR_IMAGE"
    cat << EOF >> ~/.android/avd/MyAVD.avd/config.ini
    hw.cpu.ncore=4
    hw.gpu.enabled=yes
    hw.gpu.mode=swiftshader_indirect
    hw.ramSize=4096
    disk.dataPartition.size=6G
    vm.heapSize=576
    hw.lcd.density=440
    hw.lcd.height=2220
    hw.lcd.width=1080
    EOF
  start_emulator_background_script:
    - $ANDROID_HOME/emulator/emulator @MyAVD -verbose -no-snapshot-save -no-window -noaudio -no-boot-anim -accel on
  wait_for_emulator_script:
    - android-wait-for-emulator
  patrol_develop_script: |
    cd packages/patrol/example
    dart run patrol_develop_test.dart

test_ios_task:
  name: Test `patrol develop` on macOS
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  env:
    PATH: $HOME/.pub-cache/bin:${PATH}
  timeout_in: 30m

  pub_cache:
    folder: ~/.pub-cache
  setup_simulator_script: |
    udid=$(xcrun simctl create "iPhone 14" com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-16-4)
    xcrun simctl boot "$udid"
  setup_flutter_script: |
    flutter channel stable
    flutter upgrade
    flutter precache
  setup_patrol_cli_script:
    - dart pub global activate --source path packages/patrol_cli && patrol
  patrol_test_script: |
    cd packages/patrol/example
    flutter pub get
    dart run patrol_develop_test.dart
