test_linux_task:
  name: Test `patrol develop` on Linux
  container:
    image: ghcr.io/cirruslabs/flutter:stable
    cpu: 6
    memory: 10G
    kvm: 'true'
  env:
    PATH: $HOME/.pub-cache/bin:$HOME/fvm/default/bin:$CIRRUS_WORKING_DIR/fvm:${PATH}
    EMULATOR_API_LEVEL: '34'
    EMULATOR_ABI: google_apis_playstore;x86_64
    EMULATOR_IMAGE: system-images;android-${EMULATOR_API_LEVEL};${EMULATOR_ABI}
  timeout_in: 30m

  setup_flutter_script: |
    curl -LO https://github.com/fluttertools/fvm/releases/download/2.4.1/fvm-2.4.1-linux-x64.tar.gz
    tar -xf fvm-2.4.1-linux-x64.tar.gz
    fvm install 3.7.12
    fvm global 3.7.12
    fvm doctor
    flutter --version
    flutter precache
  generate_gradlew_script: |
    cd packages/patrol/example
    flutter build apk --target lib/main.dart --debug --flavor=does-not-exist &
    start=$SECONDS
    until [ -e "android/gradlew" ] || [ $(($SECONDS - start)) -ge 120 ]; do sleep 2; done
    if [ ! -e "android/gradlew" ]; then
        echo "android/gradlew was not generated within the 2 minutes timeout"
        exit 1
    fi
    kill $!
  setup_patrol_cli_script:
    - dart pub global activate --source path packages/patrol_cli && patrol
  setup_emulator_script: |
    sdkmanager --install "$EMULATOR_IMAGE"
    sdkmanager --install emulator
  create_emulator_script: |
    avdmanager -s create avd -n MyAVD -k "$EMULATOR_IMAGE"
    cat << EOF >> ~/.android/avd/MyAVD.avd/config.ini
    hw.cpu.ncore=4
    hw.gpu.enabled=yes
    hw.gpu.mode=swiftshader_indirect
    hw.ramSize=4096
    disk.dataPartition.size=6G
    vm.heapSize=576
    hw.lcd.density=440
    hw.lcd.height=2220
    hw.lcd.width=1080
    EOF
  start_emulator_background_script:
    - $ANDROID_HOME/emulator/emulator @MyAVD -verbose -no-snapshot-save -no-window -noaudio -no-boot-anim -accel on
  wait_for_emulator_script:
    - android-wait-for-emulator
  patrol_develop_script: |
    cd dev/cli_tests
    dart pub get
    dart patrol_develop_test.dart

test_macos_task:
  name: Test `patrol develop` on macOS
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  env:
    PATH: $HOME/.pub-cache/bin:$HOME/fvm/default/bin:${PATH}
  timeout_in: 30m

  setup_flutter_script: |
    brew tap leoafarias/fvm
    brew install fvm
    fvm install 3.7.12
    fvm global 3.7.12
    fvm doctor
    flutter --version
    flutter precache
  setup_patrol_cli_script:
    - dart pub global activate --source path packages/patrol_cli && patrol
  setup_simulator_script: |
    xcrun simctl boot "iPhone 14 Pro Max"
  patrol_test_script: |
    cd dev/cli_tests
    dart pub get
    dart patrol_develop_test.dart
