test_android_task:
  name: Test example app on Android
  container:
    image: cirrusci/flutter:stable
    cpu: 8
    memory: 32G
    kvm: 'true'
  env:
    PATH: $HOME/.pub-cache/bin:${PATH}
    EMULATOR_API_LEVEL: '34'
    EMULATOR_ABI: google_apis_playstore;x86_64
    EMULATOR_IMAGE: system-images;android-${EMULATOR_API_LEVEL};${EMULATOR_ABI}
    EMULATOR_CONFIG_PATH: ~/.android/avd/MyAVD.avd/config.ini
  timeout_in: 60m

  pub_cache:
    folder: ~/.pub-cache
  setup_flutter_script:
    - flutter precache
  generate_gradlew_script: |
    cd packages/patrol/example
    flutter build apk --target lib/main.dart --debug --flavor=does-not-exist &
    buildpid="$!"
    while [ ! -e "android/gradlew" ]; do
        echo "waiting for gradlew to generate..."
        sleep 2
    done
    kill $buildpid
  setup_patrol_cli_script:
    - dart pub global activate --source path packages/patrol_cli && patrol
  setup_emulator_script:
    - sdkmanager --install "$EMULATOR_IMAGE"
    - sdkmanager --install emulator
  create_emulator_script: |
    avdmanager -s create avd -n MyAVD -k "$EMULATOR_IMAGE"
    cat << EOF >> $EMULATOR_CONFIG_PATH
    hw.gpu.enabled=yes
    hw.gpu.mode=swiftshader_indirect
    hw.ramSize=4096
    disk.dataPartition.size=6G
    vm.heapSize=576
    hw.lcd.density=440
    hw.lcd.height=2220
    hw.lcd.width=1080
    EOF
  start_emulator_background_script:
    - $ANDROID_HOME/emulator/emulator @MyAVD -verbose -no-snapshot-save -no-window -noaudio -no-boot-anim -accel on
  wait_for_emulator_script:
    - android-wait-for-emulator
  patrol_develop_script: |
    cd packages/patrol/example
    # dart run patrol_develop_test.dart

  always:
    junit_artifacts:
      path: packages/patrol/example/android/test-results/**/connected/TEST-*.xml
      type: text/xml
      format: junit

test_ios_task:
  name: Test example app on iOS simulator
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
  env:
    PATH: $HOME/.pub-cache/bin:${PATH}
  timeout_in: 30m

  pub_cache:
    folder: ~/.pub-cache
  setup_simulator_script:
    - xcrun simctl list devicetypes
    - xcrun simctl list runtimes
    # create simulator
    - udid=$(xcrun simctl create "iPhone 14" com.apple.CoreSimulator.SimDeviceType.iPhone-14 com.apple.CoreSimulator.SimRuntime.iOS-16-4)
    # boot simulator
    - xcrun simctl boot "$udid"
    - echo "UDID=$udid" >> $CIRRUS_ENV
  setup_flutter_script:
    - flutter channel stable
    - flutter upgrade
    - flutter precache
  setup_patrol_cli_script:
    - dart pub global activate --source path packages/patrol_cli && patrol
  patrol_test_script:
    - cd packages/patrol/example
    # set location
    - xcrun simctl location "$UDID" set 52.17469,21.03193
    - patrol test --device "$UDID"
      --exclude integration_test/android_app_test.dart           `# Android-only`
      --exclude integration_test/swipe_test.dart                 `# does not work on iOS`
      --exclude integration_test/service_airplane_mode_test.dart `# not available on iOS simulator`
      --exclude integration_test/service_bluetooth_test.dart     `# not available on iOS simulator`
      --exclude integration_test/service_cellular_test.dart      `# not available on iOS simulator`
      --exclude integration_test/open_quick_settings_test.dart   `# not available on iOS simulator`
      --exclude integration_test/service_wifi_test.dart          `# not available on iOS simulator`
