task:
  name: Test example app on Android
  container:
    image: cirrusci/flutter:stable
    cpu: 4
    memory: 6G
    kvm: 'true'
  env:
    PATH: $HOME/.pub-cache/bin:${PATH}
    EMULATOR_API_LEVEL: '28'
    ANDROID_ABI: 'default;x86'

  pub_cache:
    folder: ~/.pub-cache
  setup_flutter_script: flutter precache
  setup_patrol_cli_script:
    - dart pub global activate --source path packages/patrol_cli && patrol
  install_images_script: sdkmanager "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  install_emulator_script: sdkmanager emulator
  create_device_script:
    - echo no | avdmanager create avd --force -n test -k "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  start_emulator_background_script:
    - $ANDROID_HOME/emulator/emulator -no-window -verbose -avd test -no-audio -no-boot-anim
  wait_for_emulator_script: android-wait-for-emulator
  build_app_script:
    - cd packages/patrol/example
    - flutter build apk --debug
  patrol_test_script:
    - cd packages/patrol/example
    - patrol test
  always:
    junit_artifacts:
      path: packages/patrol/example/android/test-results/**/connected/TEST-*.xml
      type: text/xml
      format: junit
