#!/usr/bin/env bash

cd "$(dirname "$0")"

SRC_DIR="."

dart_out="./packages/patrol/lib/src/native/contracts"
java_out="./AutomatorServer/android/app/src/androidTest/java/pl/leancode/automatorserver/contracts"
kotlin_out="./AutomatorServer/android/app/src/androidTest/java/pl/leancode/automatorserver/contracts"
swift_out="./AutomatorServer/ios/AutomatorServerUITests"

protoc -I="$SRC_DIR" --dart_out="$dart_out" "$SRC_DIR/contracts.proto"

protoc -I="$SRC_DIR" --java_out="$java_out" --kotlin_out="$kotlin_out" "$SRC_DIR/contracts.proto"

protoc -I="$SRC_DIR" --swift_out="$swift_out" "$SRC_DIR/contracts.proto"
