#!/usr/bin/env bash
set -euo pipefail

# gen_from_schema generates classes from schema.dart for every used language
# (Dart, Swift, Kotlin/Java) in the appropriate directory.

cd "$(dirname "$0")" || exit

schema="./schema.dart"
patrol_package="./packages/patrol"
patrol_dart_out_dir="lib/src/native/contracts"

ios_out="$patrol_package/ios/Classes/AutomatorServer"
dart_out="$patrol_package/$patrol_dart_out_dir"

android_out="$patrol_package/android/src/main/kotlin/pl/leancode/patrol/contracts"
android_package="pl.leancode.patrol.contracts"

macos_out="$patrol_package/macos/Classes/AutomatorServer"

dart run packages/patrol_gen/bin/main.dart "$schema" "$dart_out" "$ios_out" "$android_out" "$android_package" "$macos_out"

cd "${patrol_package}"
dart run build_runner build --delete-conflicting-outputs --build-filter="$patrol_dart_out_dir/*.dart"
