#!/usr/bin/env bash
set -euo pipefail

# gen_protobufs generates Protocol Buffers classes for every used language
# (Dart, Swift, Kotlin/Java) in the appropriate directory.
#
# To use it, you need to have the following programs in your $PATH:
#
#  * protoc
#
#  * Dart plugin
#	dart pub global activate protoc_plugin 20.0.1
#	
#	More details:
#	- https://pub.dev/packages/protoc_plugin
#
#  * Swift plugin: 
#	brew install grpc-swift@1.18.0
#	brew install swift-protobuf@1.22.1
#	
# 	More details:
#	- https://github.com/apple/swift-protobuf
#	- https://github.com/grpc/grpc-swift
#    
#  * Java plugin
#	https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.49.1/
#	mv protoc-gen-grpc-java-1.49.1-osx-x86_64.exe protoc-gen-grpc-java
#	chmod 755 protoc-gen-grpc-java
#
#	More details:
#	- https://github.com/grpc/grpc-java
#	- https://github.com/grpc/grpc-java/blob/master/compiler/README.md
#
#  * Kotlin plugin
#	https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-kotlin/1.3.0/
#	
#	More details:
#	- https://github.com/grpc/grpc-kotlin/tree/master/compiler

cd "$(dirname "$0")" || exit

SRC_DIR="."
PROTO_PATH="./contracts.proto"

mkdir -p ./patrol/packages/patrol/android/src/main/kotlin
mkdir -p ./packages/patrol/ios/Classes/AutomatorServer

dart_out="./packages/patrol/lib/src/native/contracts"
java_out="packages/patrol/android/src/main/kotlin"
kotlin_out="$java_out"
swift_out="./packages/patrol/ios/Classes/AutomatorServer"

protoc \
	--dart_out="grpc:$dart_out" \
	-I="$SRC_DIR" \
	"$PROTO_PATH"

protoc \
	--java_out="lite:$java_out" \
	--kotlin_out="lite:$kotlin_out" \
	--grpc-java_out="lite:$java_out" \
	--grpckt_out="lite:$kotlin_out" \
	"$PROTO_PATH"

protoc \
	--swift_out="$swift_out" \
	--grpc-swift_out="$swift_out" \
	--swift_opt=Visibility=Public \
	"$PROTO_PATH"

dart format "$dart_out/contracts.pb.dart"
dart format "$dart_out/contracts.pbenum.dart"
dart format "$dart_out/contracts.pbjson.dart"