name: Patrol

packages:
  - packages/**

scripts:
  get:
    run: melos exec flutter pub get

  analyze:
    run: melos exec flutter analyze

  format:
    run: melos exec dart format .

  test:
    run: melos exec flutter test
    select-package:
      dir-exists:
        - test
