include: package:leancode_lint/analysis_options.yaml

linter:
  rules:
    prefer_const_constructors: false
    avoid_print: false

analyzer:
  errors:
    deprecated_member_use: ignore # TODO: Remove after deprections are fixed
