//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.patrol.automator.contracts;

@kotlin.jvm.JvmName("-initializeempty")
public inline fun empty(block: pl.leancode.patrol.automator.contracts.EmptyKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.automator.contracts.Contracts.Empty =
  pl.leancode.patrol.automator.contracts.EmptyKt.Dsl._create(pl.leancode.patrol.automator.contracts.Contracts.Empty.newBuilder()).apply { block() }._build()
public object EmptyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pl.leancode.patrol.automator.contracts.Contracts.Empty.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.patrol.automator.contracts.Contracts.Empty.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.patrol.automator.contracts.Contracts.Empty = _builder.build()
  }
}
public inline fun pl.leancode.patrol.automator.contracts.Contracts.Empty.copy(block: pl.leancode.patrol.automator.contracts.EmptyKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.automator.contracts.Contracts.Empty =
  pl.leancode.patrol.automator.contracts.EmptyKt.Dsl._create(this.toBuilder()).apply { block() }._build()
