//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.patrol.automator.contracts;

@kotlin.jvm.JvmName("-initializehandlePermissionRequest")
public inline fun handlePermissionRequest(block: pl.leancode.patrol.automator.contracts.HandlePermissionRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.automator.contracts.Contracts.HandlePermissionRequest =
  pl.leancode.patrol.automator.contracts.HandlePermissionRequestKt.Dsl._create(pl.leancode.patrol.automator.contracts.Contracts.HandlePermissionRequest.newBuilder()).apply { block() }._build()
public object HandlePermissionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pl.leancode.patrol.automator.contracts.Contracts.HandlePermissionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.patrol.automator.contracts.Contracts.HandlePermissionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.patrol.automator.contracts.Contracts.HandlePermissionRequest = _builder.build()

    /**
     * <code>.patrol.HandlePermissionRequest.Code code = 1;</code>
     */
    public var code: pl.leancode.patrol.automator.contracts.Contracts.HandlePermissionRequest.Code
      @JvmName("getCode")
      get() = _builder.getCode()
      @JvmName("setCode")
      set(value) {
        _builder.setCode(value)
      }
    /**
     * <code>.patrol.HandlePermissionRequest.Code code = 1;</code>
     */
    public fun clearCode() {
      _builder.clearCode()
    }
  }
}
public inline fun pl.leancode.patrol.automator.contracts.Contracts.HandlePermissionRequest.copy(block: pl.leancode.patrol.automator.contracts.HandlePermissionRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.automator.contracts.Contracts.HandlePermissionRequest =
  pl.leancode.patrol.automator.contracts.HandlePermissionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
