name: patrol_finders_example
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.41.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^24.0.0
  patrol_finders:
    path: ../

dependency_overrides:
  # Match *at least* Flutter 3.41's meta dependency
  meta: ^1.17.0

flutter:
  uses-material-design: true
