//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package patrol;

@kotlin.jvm.JvmName("-initializeenterTextBySelectorCommand")
inline fun enterTextBySelectorCommand(block: patrol.EnterTextBySelectorCommandKt.Dsl.() -> kotlin.Unit): patrol.Contracts.EnterTextBySelectorCommand =
  patrol.EnterTextBySelectorCommandKt.Dsl._create(patrol.Contracts.EnterTextBySelectorCommand.newBuilder()).apply { block() }._build()
object EnterTextBySelectorCommandKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: patrol.Contracts.EnterTextBySelectorCommand.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: patrol.Contracts.EnterTextBySelectorCommand.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): patrol.Contracts.EnterTextBySelectorCommand = _builder.build()

    /**
     * <code>string appId = 1;</code>
     */
    var appId: kotlin.String
      @JvmName("getAppId")
      get() = _builder.getAppId()
      @JvmName("setAppId")
      set(value) {
        _builder.setAppId(value)
      }
    /**
     * <code>string appId = 1;</code>
     */
    fun clearAppId() {
      _builder.clearAppId()
    }

    /**
     * <code>string data = 2;</code>
     */
    var data: kotlin.String
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * <code>string data = 2;</code>
     */
    fun clearData() {
      _builder.clearData()
    }

    /**
     * <code>.patrol.Selector selector = 3;</code>
     */
    var selector: patrol.Contracts.Selector
      @JvmName("getSelector")
      get() = _builder.getSelector()
      @JvmName("setSelector")
      set(value) {
        _builder.setSelector(value)
      }
    /**
     * <code>.patrol.Selector selector = 3;</code>
     */
    fun clearSelector() {
      _builder.clearSelector()
    }
    /**
     * <code>.patrol.Selector selector = 3;</code>
     * @return Whether the selector field is set.
     */
    fun hasSelector(): kotlin.Boolean {
      return _builder.hasSelector()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun patrol.Contracts.EnterTextBySelectorCommand.copy(block: patrol.EnterTextBySelectorCommandKt.Dsl.() -> kotlin.Unit): patrol.Contracts.EnterTextBySelectorCommand =
  patrol.EnterTextBySelectorCommandKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val patrol.Contracts.EnterTextBySelectorCommandOrBuilder.selectorOrNull: patrol.Contracts.Selector?
  get() = if (hasSelector()) getSelector() else null

