//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package patrol;

@kotlin.jvm.JvmName("-initializeenterTextByIndexCommand")
inline fun enterTextByIndexCommand(block: patrol.EnterTextByIndexCommandKt.Dsl.() -> kotlin.Unit): patrol.Contracts.EnterTextByIndexCommand =
  patrol.EnterTextByIndexCommandKt.Dsl._create(patrol.Contracts.EnterTextByIndexCommand.newBuilder()).apply { block() }._build()
object EnterTextByIndexCommandKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: patrol.Contracts.EnterTextByIndexCommand.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: patrol.Contracts.EnterTextByIndexCommand.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): patrol.Contracts.EnterTextByIndexCommand = _builder.build()

    /**
     * <code>string appId = 1;</code>
     */
    var appId: kotlin.String
      @JvmName("getAppId")
      get() = _builder.getAppId()
      @JvmName("setAppId")
      set(value) {
        _builder.setAppId(value)
      }
    /**
     * <code>string appId = 1;</code>
     */
    fun clearAppId() {
      _builder.clearAppId()
    }

    /**
     * <code>string data = 2;</code>
     */
    var data: kotlin.String
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * <code>string data = 2;</code>
     */
    fun clearData() {
      _builder.clearData()
    }

    /**
     * <pre>
     * TODO: should be uint32?
     * </pre>
     *
     * <code>int32 index = 3;</code>
     */
    var index: kotlin.Int
      @JvmName("getIndex")
      get() = _builder.getIndex()
      @JvmName("setIndex")
      set(value) {
        _builder.setIndex(value)
      }
    /**
     * <pre>
     * TODO: should be uint32?
     * </pre>
     *
     * <code>int32 index = 3;</code>
     */
    fun clearIndex() {
      _builder.clearIndex()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun patrol.Contracts.EnterTextByIndexCommand.copy(block: patrol.EnterTextByIndexCommandKt.Dsl.() -> kotlin.Unit): patrol.Contracts.EnterTextByIndexCommand =
  patrol.EnterTextByIndexCommandKt.Dsl._create(this.toBuilder()).apply { block() }._build()

