@import Foundation;

NS_ASSUME_NONNULL_BEGIN

@interface PatrolUtils : NSObject

/**
 * Converts test group names in Dart (generated by Patrol CLI) into a valid Objective-C method name.
 *
 * example_test -> example_test
 * example.example_test -> example_exampleTest
 * very.deep.example_test -> very_deep_exampleTest
 */
+ (NSString *)createMethodNameFromPatrolGeneratedGroup:(NSString *)dartTestGroup;
@end

NS_ASSUME_NONNULL_END
