#!/usr/bin/env bash
set -euo pipefail

# makearchive is a convenience program which creates a zip archive of the iOS
# AutomatorServer.

if [ "$(basename "$PWD")" = "ios" ]; then
    zip -r
else
	echo "this program must be run from the ios project directory"
	exit 1
fi
