#!/usr/bin/env bash
set -euo pipefail

mkdir -p ./artifacts

xcodebuild \
    -project AutomatorServer.xcodeproj \
    -scheme AutomatorServer \
    -derivedDataPath ./DerivedData \
    -sdk iphonesimulator \
    -arch arm64

cp -r \
    ./DerivedData/Build/Products/Debug-iphoneimulator/AutomatorServer.app \
    ./artifacts/AutomatorServer-iphoneimulator-arm64.app

xcodebuild \
    -project AutomatorServer.xcodeproj \
    -scheme AutomatorServer \
    -derivedDataPath ./DerivedData \
    -sdk iphonesimulator \
    -arch x86_64

cp -r \
    ./DerivedData/Build/Products/Debug-iphoneimulator/AutomatorServer.app \
    ./artifacts/AutomatorServer-iphoneimulator-x86_64.app

xcodebuild \
    -project AutomatorServer.xcodeproj \
    -scheme AutomatorServer \
    -derivedDataPath ./DerivedData \
    -sdk iphoneos

cp -r \
    ./DerivedData/Build/Products/Debug-iphoneimulator/AutomatorServer.app \
    ./artifacts/AutomatorServer-iphoneos.app
