#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")"

sdk="${1:-}"
arch="${2:-}"
version="${3:-}"

if [ -z "$sdk" ] || [ -z "$arch" ] || [ -z "$version" ]; then
    echo "usage: ./make_artifacts <sdk> <arch> <version>"
    exit 1
fi


args=(
    -project AutomatorServer.xcodeproj
    -scheme AutomatorServerUITests
    -derivedDataPath ./DerivedData
    -sdk "$sdk"
    -arch "$arch"
)

if [ "$sdk" == "iphonesimulator" ]; then
    args+=(CODE_SIGN_IDENTITY="")
    args+=(CODE_SIGNING_REQUIRED="NO")
    args+=(CODE_SIGN_ENTITLEMENTS="")
    args+=(CODE_SIGNING_ALLOWED="NO")
fi
# else
#     args+=(PROVISIONING_PROFILE="a3fa47d1-b647-4a95-b66d-7f54d0bcb975")
# fi

echo "arguments to xcodebuild build-for-testing:"
for arg in "${args[@]}"; do
    echo "arg: $arg"
done

mkdir -p ./artifacts

xcodebuild build-for-testing "${args[@]}"

cp -r \
    "./DerivedData/Build/Products/Debug-$sdk/AutomatorServerUITests-Runner.app" \
    "./artifacts/AutomatorServer-$sdk-$arch-$version.app"

cd ./artifacts
zip -r "AutomatorServer-$sdk-$arch-$version.zip" "AutomatorServer-$sdk-$arch-$version.app"
cd ..
