#!/usr/bin/env bash
set -euo pipefail

# makearchive is a convenience program which creates a zip archive of the iOS
# AutomatorServer.

version="${1:-}"

if [ -z "$version" ]; then
	echo "usage: makearchive <version>"
	echo "example: makearchive 2.4.1"
	exit 1
fi

if [ "$(basename "$PWD")" = "ios" ]; then
    zip -r "../ios-$version.zip" .
else
	echo "this program must be run from the ios project directory"
	exit 1
fi
