#!/usr/bin/env bash
set -euo pipefail

# run_tests runs a basic test suite to ensure that the server works. It requires
# `http` command (see https://httpie.io) and a running iOS automation server
# running on port 8081.


times="${1:-10}"
if [ -z "$times" ]; then
    echo "Specify how many times you want to run a test"
    exit 1
fi

for _ in $(seq 0 "$times"); do
    http GET localhost:8081/isRunning
    http POST localhost:8081/openApp id='pl.baftek.discoverRudy'
    http POST localhost:8081/pressHome || true
done
