name: Request a feature
description: |
  Suggest a new idea to make Patrol better.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using Patrol!

        If you're looking for support, check out our docs or consider asking a
        question on our Discussions or Stack Overflow:

          - https://patrol.leancode.co
          - https://github.com/leancodepl/patrol/discussions
          - https://stackoverflow.com/questions/tagged/flutter-patrol

        Please search the [existing issues] to see if an issue already exists
        for the feature you need.

        ---

        If you are sure that you have found a feature that hasn't been requested
        yet, or if our documentation doesn't have an answer to what you're
        looking for, then fill out the template below. Please bear in mind that
        duplicates and unsufficiently described feature requests will be closed.

        [existing issues]: https://github.com/leancodepl/patrol/issues
  - type: textarea
    attributes:
      label: Use case
      description: |
        Please tell us the problem you are running into that led to you wanting
        a new feature.

        Is your feature request related to a problem? Please give a clear and
        concise description of what the problem is.

        Describe the alternative solutions you've considered and the tradeoffs
        they come with.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: |
        Briefly but precisely describe what the new feature would look like.

        Consider attaching something showing what you are imagining:
         * code samples
         * API design ideas
    validations:
      required: true
