name: patrol_mcp
description: >
  An MCP server that empowers AI assistants to control, automate, and monitor
  interactive Patrol development sessions in Flutter.
version: 0.1.2
homepage: https://patrol.leancode.co
repository: https://github.com/leancodepl/patrol/tree/master/packages/patrol_mcp
issue_tracker: https://github.com/leancodepl/patrol/issues
documentation: https://patrol.leancode.co
topics: [test, e2e, flutter-test, claude, ai]

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  adb: ^0.6.0
  args: ^2.7.0
  dispose_scope: ^2.1.0
  image: ^4.5.4
  logging: ^1.3.0
  mcp_dart: ^2.1.0
  path: ^1.9.1
  patrol_cli: ^4.3.0

dev_dependencies:
  leancode_lint: ^17.0.0

