include: package:leancode_lint/analysis_options_package.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - lib/**/*.g.dart
    - lib/src/server_port/android_server_port_provider_bindings.dart
