name: Tag New Release
on:
    workflow_dispatch:
        inputs:
            releaseVersion:
                description: 'The version/tag of the release'
                required: true

jobs:
    update_spm:
        runs-on: ubuntu-latest
        steps:

          - name: Checkout main branch
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            with:
                ref: main

          - name: Create and push tag
            run: |
                git tag -a ${{ steps.get_latest_release.outputs.version }} -m "Release ${{ steps.get_latest_release.outputs.version }}"
                git push origin tag ${{ steps.get_latest_release.outputs.version }}

          - name: Create GitHub release
            uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
            with:
                tag_name: ${{ steps.get_latest_release.outputs.version }}
                release_name: ${{ steps.get_latest_release.outputs.version }}
                generate_release_notes: true
                draft: false
                prerelease: false
