// Terminology note:
// "Run a test" is used interchangeably with "execute a test".
// "Run a Dart test" is used interchangeably with "request execution of a Dart test" and "execute a Dart test".
// "ATO" is short for "Android Test Orchestrator".

package pl.leancode.patrol;

import static org.junit.Assume.*;

import android.app.Instrumentation;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import androidx.test.platform.app.InstrumentationRegistry;
import androidx.test.runner.AndroidJUnitRunner;
import androidx.test.uiautomator.UiDevice;

import pl.leancode.patrol.contracts.Contracts;
import pl.leancode.patrol.contracts.PatrolAppServiceClientException;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static pl.leancode.patrol.contracts.Contracts.DartGroupEntry;
import static pl.leancode.patrol.contracts.Contracts.RunDartTestResponse;

/**
 * <p>
 * A customized AndroidJUnitRunner that enables Patrol on Android.
 * </p>
 */
public class PatrolJUnitRunner extends AndroidJUnitRunner {
    private static final String TARGET_APP_ID_ARGUMENT = "patrolAppId";
    private static final String TARGET_APP_ID_METADATA = "pl.leancode.patrol.APP_ID";
    private static final String CLEAR_APP_DATA_ARGUMENT = "patrolClearAppData";
    private static final String CLEAR_APP_DATA_METADATA = "pl.leancode.patrol.CLEAR_APP_DATA";

    public PatrolAppServiceClient patrolAppServiceClient;
    private Map<String, Boolean> dartTestCaseSkipMap = new HashMap<>();
    private boolean generatedSetUpDone = false;

    /** Simple name of the class written by build-time test discovery (`patrol build android --emit-test-manifest`). */
    private static final String GENERATED_TESTS_CLASS = "PatrolGeneratedTests";

    private String targetAppId;
    private boolean clearAppData;

    @Override
    protected boolean shouldWaitForActivitiesToComplete() {
        return false;
    }

    @Override
    public void onCreate(Bundle arguments) {
        targetAppId = arguments.getString(TARGET_APP_ID_ARGUMENT);
        final String clearAppDataArgument = arguments.getString(CLEAR_APP_DATA_ARGUMENT);

        // Register the listener that records each test's JUnit name for screenshots.
        String listeners = arguments.getString("listener");
        String patrolListener = PatrolTestNameListener.class.getName();
        arguments.putString(
                "listener",
                listeners == null || listeners.isEmpty()
                        ? patrolListener
                        : listeners + "," + patrolListener
        );

        super.onCreate(arguments);

        if (targetAppId == null || targetAppId.isEmpty()) {
            targetAppId = readInstrumentationMetadata(TARGET_APP_ID_METADATA);
        }
        if (clearAppDataArgument == null) {
            clearAppData = Boolean.parseBoolean(
                    readInstrumentationMetadata(CLEAR_APP_DATA_METADATA)
            );
        } else {
            clearAppData = Boolean.parseBoolean(clearAppDataArgument);
        }

        // This is only true when the ATO requests a list of tests from the app during the initial run.
        boolean isInitialRun = Boolean.parseBoolean(arguments.getString("listTestsForOrchestrator"));

        Logger.INSTANCE.i("--------------------------------");
        Logger.INSTANCE.i("PatrolJUnitRunner.onCreate() " + (isInitialRun ? "(initial run)" : ""));
    }

    @Override
    public void finish(int resultCode, Bundle results) {
        if (patrolAppServiceClient != null) {
            try {
                patrolAppServiceClient.close();
            } catch (Exception e) {
                Logger.INSTANCE.e("Failed to close PatrolAppServiceClient", e);
            }
        }
        super.finish(resultCode, results);
    }

    /**
     * Starts Patrol and launches the supplied activity in the instrumentation target.
     */
    public void setUp(Class<?> activityClass) {
        if (isSupersededByGeneratedTests()) {
            Logger.INSTANCE.i("PatrolJUnitRunner.setUp(): standing down, " + GENERATED_TESTS_CLASS + " runs these tests");
            return;
        }

        Instrumentation instrumentation = InstrumentationRegistry.getInstrumentation();
        setUp(
                instrumentation.getTargetContext().getPackageName(),
                activityClass.getCanonicalName()
        );
    }

    /**
     * Starts Patrol and launches the configured app under test.
     */
    public void setUp() {
        if (isSupersededByGeneratedTests()) {
            Logger.INSTANCE.i("PatrolJUnitRunner.setUp(): standing down, " + GENERATED_TESTS_CLASS + " runs these tests");
            return;
        }

        setUp(requireTargetAppId(), null);
    }

    /**
     * <p>
     * Sets up and awaits the app for the test classes generated by build-time test discovery
     * ({@code patrol build --emit-test-manifest}).
     * </p>
     *
     * <p>
     * Equivalent to {@link #setUp(Class)} followed by {@link #waitForPatrolAppService()}, except it
     * never stands down: the generated classes hold the tests themselves, so nothing supersedes
     * them. Keeping them on their own entry point is what lets the stand-down check stay a plain
     * "is there a generated class next to the host" question. Only the first call launches the app;
     * the calls from the remaining generated classes in the process are no-ops.
     * </p>
     */
    public void setUpGenerated(Class<?> activityClass) {
        if (!beginGeneratedSetUp()) {
            return;
        }

        Instrumentation instrumentation = InstrumentationRegistry.getInstrumentation();
        setUp(
                instrumentation.getTargetContext().getPackageName(),
                activityClass.getCanonicalName()
        );
        awaitPatrolAppService();
    }

    /**
     * <p>
     * {@link #setUpGenerated(Class)} for the self-instrumenting {@code :patrolTest} layout, where
     * the app under test is a different package and its ID comes from the test APK's metadata
     * instead of an activity class.
     * </p>
     */
    public void setUpGenerated() {
        if (!beginGeneratedSetUp()) {
            return;
        }

        setUp(requireTargetAppId(), null);
        awaitPatrolAppService();
    }

    /**
     * Whether this is the call that should launch the app for the generated test classes.
     */
    private boolean beginGeneratedSetUp() {
        // Each generated class calls setUpGenerated from @BeforeClass, and without the ATO
        // they all share one instrumentation process. The server binds a fixed
        // port, so launch once and reuse it (same as the iOS static runner).
        if (generatedSetUpDone) {
            return false;
        }
        generatedSetUpDone = true;
        return true;
    }

    private String requireTargetAppId() {
        if (targetAppId == null || targetAppId.isEmpty()) {
            throw new IllegalStateException(
                    "Missing the app under test's application ID. Apply "
                            + "patrol_test.gradle from :patrolTest so it can bake "
                            + TARGET_APP_ID_METADATA
                            + " into the test APK, or pass instrumentation argument '"
                            + TARGET_APP_ID_ARGUMENT
                            + "'."
            );
        }
        return targetAppId;
    }

    public void setUp(String appId) {
        setUp(appId, null);
    }

    public void setUp(String appId, String activityClassName) {
        Logger.INSTANCE.i(
                "PatrolJUnitRunner.setUp(): appId = " + appId
                        + ", activityClassName = " + activityClassName
        );
        targetAppId = appId;

        if (clearAppData) {
            clearAppData(appId);
        } else if (isSelfInstrumenting()) {
            // Orchestrator starts a new tester process per JUnit case. A launcher
            // intent only foregrounds an already-running app, whose Dart explorer
            // will not signal ready again. Stop it so this process gets a fresh one.
            forceStopApp(appId);
        }

        PatrolServer patrolServer = new PatrolServer();
        patrolServer.start();

        launchApp(appId, activityClassName);
        patrolAppServiceClient = createAppServiceClient();
    }

    private void launchApp(String appId, String activityClassName) {
        Instrumentation instrumentation = InstrumentationRegistry.getInstrumentation();

        // Launcher intents support activities declared through aliases.
        Intent intent = instrumentation.getContext().getPackageManager()
                .getLaunchIntentForPackage(appId);

        if (intent == null && activityClassName != null) {
            intent = new Intent(Intent.ACTION_MAIN);
            intent.setClassName(appId, activityClassName);
        }

        if (intent == null) {
            throw new IllegalStateException("No launch intent found for " + appId);
        }

        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        instrumentation.getContext().startActivity(intent);
    }

    public PatrolAppServiceClient createAppServiceClient() {
        return new PatrolAppServiceClient();
    }

    /**
     * <p>
     * Whether the instrumentation targets its own package, i.e. the runner runs in a
     * separate process from the app under test.
     * </p>
     */
    private boolean isSelfInstrumenting() {
        return getContext().getPackageName().equals(getTargetContext().getPackageName());
    }

    /**
     * Reads a value embedded in the test APK at assemble time.
     */
    private String readInstrumentationMetadata(String name) {
        try {
            android.content.pm.ApplicationInfo info =
                    getContext()
                            .getPackageManager()
                            .getApplicationInfo(
                                    getContext().getPackageName(),
                                    android.content.pm.PackageManager.GET_META_DATA
                            );
            if (info.metaData == null) {
                return null;
            }
            Object value = info.metaData.get(name);
            return value == null ? null : String.valueOf(value);
        } catch (android.content.pm.PackageManager.NameNotFoundException e) {
            return null;
        }
    }

    /**
     * <p>
     * Wipes the app's data (shared preferences, databases, files, granted runtime
     * permissions) so the next Dart test starts from a clean install-like state.
     * </p>
     *
     * <p>
     * This is only possible when the runner lives outside the app process. Clearing
     * the package that hosts the instrumentation would kill the test run itself.
     * </p>
     */
    private void clearAppData(String appId) {
        if (!appId.matches("[A-Za-z0-9._]+")) {
            throw new IllegalArgumentException("Invalid Android package name: " + appId);
        }

        if (!isSelfInstrumenting()) {
            throw new IllegalStateException(
                    "Clearing app data requires the Patrol test module, because clearing "
                            + appId + " would also kill the instrumentation hosted in it."
            );
        }

        Logger.INSTANCE.i("PatrolJUnitRunner: clearing app data of " + appId);

        final String output;
        try {
            output = UiDevice.getInstance(this).executeShellCommand("pm clear " + appId);
        } catch (IOException e) {
            throw new RuntimeException("Failed to clear app data of " + appId, e);
        }

        // A missing or not-yet-installed package reports "Failed"; treat that as fatal
        // rather than silently running without isolation.
        if (output == null || !output.contains("Success")) {
            throw new IllegalStateException(
                    "Failed to clear app data of " + appId + ": " + output
            );
        }
    }

    /**
     * Stops the app under test without wiping its data. Safe only when the runner
     * is not hosted in that app.
     */
    private void forceStopApp(String appId) {
        if (!appId.matches("[A-Za-z0-9._]+")) {
            throw new IllegalArgumentException("Invalid Android package name: " + appId);
        }

        Logger.INSTANCE.i("PatrolJUnitRunner: force-stopping " + appId);

        try {
            UiDevice.getInstance(this).executeShellCommand("am force-stop " + appId);
        } catch (IOException e) {
            throw new RuntimeException("Failed to force-stop " + appId, e);
        }
    }

    /**
     * <p>
     * Waits until PatrolAppService, running in the Dart side of the app, reports
     * that it's ready to be asked about the list of Dart tests.
     * </p>
     *
     * <p>
     * PatrolAppService becomes ready once the special Dart test named "patrol_test_explorer" finishes running.
     * </p>
     */
    public void waitForPatrolAppService() {
        if (isSupersededByGeneratedTests()) {
            return;
        }

        awaitPatrolAppService();
    }

    private void awaitPatrolAppService() {
        final String TAG = "PatrolJUnitRunner.setUp(): ";

        Logger.INSTANCE.i(TAG + "Waiting for PatrolAppService to report its readiness...");
        PatrolServer.Companion.getAppReady().block();

        Logger.INSTANCE.i(TAG + "PatrolAppService is ready to report Dart tests");
    }

    public Object[] listDartTests() {
        final String TAG = "PatrolJUnitRunner.listDartTests(): ";

        if (isSupersededByGeneratedTests()) {
            Logger.INSTANCE.i(TAG + "Reporting no tests, " + GENERATED_TESTS_CLASS + " covers the whole Dart test suite");
            return new Object[]{};
        }

        try {
            final DartGroupEntry dartTestGroup = patrolAppServiceClient.listDartTests();
            List<DartGroupEntry> dartTestCases = ContractsExtensionsKt.listTestsFlat(dartTestGroup, "");
            List<String> dartTestCaseNamesList = new ArrayList<>();
            for (DartGroupEntry dartTestCase : dartTestCases) {
                dartTestCaseSkipMap.put(dartTestCase.getName(), dartTestCase.getSkip());
                dartTestCaseNamesList.add(dartTestCase.getName());
            }
            Object[] dartTestCaseNames = dartTestCaseNamesList.toArray();
            Logger.INSTANCE.i(TAG + "Got Dart tests: " + Arrays.toString(dartTestCaseNames));
            return dartTestCaseNames;
        } catch (PatrolAppServiceClientException e) {
            Logger.INSTANCE.e(TAG + "Failed to list Dart tests: ", e);
            throw new RuntimeException(e);
        }
    }

    /**
     * <p>
     * Whether the calling test class must contribute no tests because build-time test discovery
     * compiled its generated class into the same APK.
     * </p>
     *
     * <p>
     * The generated class and the runtime-discovery host class each run the entire Dart suite, so
     * leaving both active runs everything twice. {@code patrol test} selects the generated class
     * explicitly, but any other runner (Firebase Test Lab, saucectl, emulator.wtf, Marathon)
     * instruments the APK as built.
     * </p>
     */
    private boolean isSupersededByGeneratedTests() {
        for (StackTraceElement frame : new Throwable().getStackTrace()) {
            final String caller = frame.getClassName();
            if (caller.equals(PatrolJUnitRunner.class.getName()) || caller.equals(getClass().getName())) {
                continue;
            }
            return isSupersededByGeneratedTests(caller);
        }
        return false;
    }

    /**
     * Whether a generated test class sits next to {@code callerClassName}, which is then the host
     * class it supersedes. The generated classes drive the runner through
     * {@link #setUpGenerated(Class)} and never reach this check, so the caller here is always a
     * host candidate.
     */
    static boolean isSupersededByGeneratedTests(String callerClassName) {
        final int packageEnd = callerClassName.lastIndexOf('.');
        if (packageEnd < 0 || callerClassName.substring(packageEnd + 1).equals(GENERATED_TESTS_CLASS)) {
            return false;
        }

        try {
            Class.forName(callerClassName.substring(0, packageEnd + 1) + GENERATED_TESTS_CLASS);
            return true;
        } catch (ClassNotFoundException e) {
            return false;
        }
    }

    /**
     * Requests execution of a Dart test and waits for it to finish.
     * Throws AssertionError if the test fails.
     */
    public RunDartTestResponse runDartTest(String name) {
        // Runtime-discovery path: the skip flag was recorded by listDartTests().
        // Guard against a missing entry so a null Boolean can't NPE on unboxing.
        final Boolean skip = dartTestCaseSkipMap.get(name);
        return runDartTest(name, Boolean.TRUE.equals(skip));
    }

    /**
     * Requests execution of a Dart test and waits for it to finish.
     * Throws AssertionError if the test fails.
     *
     * <p>
     * This overload takes the [skip] flag explicitly, so it works without a
     * prior {@link #listDartTests()} call. It's used by the statically generated
     * test class produced by build-time test discovery
     * (`patrol build android --emit-test-manifest`).
     * </p>
     */
    public RunDartTestResponse runDartTest(String name, boolean skip) {
        final String TAG = "PatrolJUnitRunner.runDartTest(" + name + "): ";

        if (skip) {
            Logger.INSTANCE.i(TAG + "Test skipped");
            assumeFalse(skip);
        }

        try {
            Logger.INSTANCE.i(TAG + "Requested execution");
            RunDartTestResponse response = patrolAppServiceClient.runDartTest(name);

            while (response.getResult() == Contracts.RunDartTestResponseResult.continuation) {
                if (!isSelfInstrumenting()) {
                    throw new IllegalStateException(
                            "Phased Patrol tests require the self-instrumenting "
                                    + ":patrolTest Android layout"
                    );
                }

                final Long nextPhaseIndex = response.getNextPhaseIndex();
                if (nextPhaseIndex == null) {
                    throw new IllegalStateException(
                            "A phased Patrol test returned continuation without a next phase"
                    );
                }

                closePatrolAppServiceClient();
                PatrolServer.Companion.getAppReady().close();
                forceStopApp(targetAppId);
                openApp(targetAppId, response.getNextPhaseLaunchUrl());

                waitForPatrolAppService();
                patrolAppServiceClient = createAppServiceClient();
                response = patrolAppServiceClient.runDartTest(name, nextPhaseIndex);
            }

            if (response.getResult() == Contracts.RunDartTestResponseResult.failure) {
                throw new AssertionError("Dart test failed: " + name + "\n" + response.getDetails());
            }
            // The app can skip a test the native side was told to run, for example when a
            // platform-dependent `skip:` was evaluated differently during build-time discovery.
            if (response.getResult() == Contracts.RunDartTestResponseResult.skipped) {
                Logger.INSTANCE.i(TAG + "Test skipped by the app: " + response.getDetails());
                assumeTrue(response.getDetails(), false);
            }
            Logger.INSTANCE.i(TAG + "Test execution succeeded");
            return response;
        } catch (PatrolAppServiceClientException e) {
            Logger.INSTANCE.e(TAG + e.getMessage(), e.getCause());
            throw new RuntimeException(e);
        }
    }

    private void openApp(String appId, String url) {
        if (url == null || url.isEmpty()) {
            launchApp(appId, null);
            return;
        }

        Instrumentation instrumentation = InstrumentationRegistry.getInstrumentation();
        Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(url));
        intent.setPackage(appId);
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        instrumentation.getContext().startActivity(intent);
    }

    private void closePatrolAppServiceClient() {
        if (patrolAppServiceClient == null) {
            return;
        }
        patrolAppServiceClient.close();
        patrolAppServiceClient = null;
    }
}
