//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializecellularResponse")
inline fun cellularResponse(block: pl.leancode.automatorserver.contracts.CellularResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.CellularResponse =
  pl.leancode.automatorserver.contracts.CellularResponseKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.CellularResponse.newBuilder()).apply { block() }._build()
object CellularResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.CellularResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.CellularResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.CellularResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.CellularResponse.copy(block: pl.leancode.automatorserver.contracts.CellularResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.CellularResponse =
  pl.leancode.automatorserver.contracts.CellularResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

