//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializedefaultResponse")
inline fun defaultResponse(block: pl.leancode.automatorserver.contracts.DefaultResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.DefaultResponse =
  pl.leancode.automatorserver.contracts.DefaultResponseKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.DefaultResponse.newBuilder()).apply { block() }._build()
object DefaultResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.DefaultResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.DefaultResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.DefaultResponse = _builder.build()

    /**
     * <code>string errorMessage = 1;</code>
     */
    var errorMessage: kotlin.String
      @JvmName("getErrorMessage")
      get() = _builder.getErrorMessage()
      @JvmName("setErrorMessage")
      set(value) {
        _builder.setErrorMessage(value)
      }
    /**
     * <code>string errorMessage = 1;</code>
     */
    fun clearErrorMessage() {
      _builder.clearErrorMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.DefaultResponse.copy(block: pl.leancode.automatorserver.contracts.DefaultResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.DefaultResponse =
  pl.leancode.automatorserver.contracts.DefaultResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

