//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializedoublePressRecentAppsResponse")
inline fun doublePressRecentAppsResponse(block: pl.leancode.automatorserver.contracts.DoublePressRecentAppsResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.DoublePressRecentAppsResponse =
  pl.leancode.automatorserver.contracts.DoublePressRecentAppsResponseKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.DoublePressRecentAppsResponse.newBuilder()).apply { block() }._build()
object DoublePressRecentAppsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.DoublePressRecentAppsResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.DoublePressRecentAppsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.DoublePressRecentAppsResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.DoublePressRecentAppsResponse.copy(block: pl.leancode.automatorserver.contracts.DoublePressRecentAppsResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.DoublePressRecentAppsResponse =
  pl.leancode.automatorserver.contracts.DoublePressRecentAppsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

