//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializeenterTextResponse")
inline fun enterTextResponse(block: pl.leancode.automatorserver.contracts.EnterTextResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.EnterTextResponse =
  pl.leancode.automatorserver.contracts.EnterTextResponseKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.EnterTextResponse.newBuilder()).apply { block() }._build()
object EnterTextResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.EnterTextResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.EnterTextResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.EnterTextResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.EnterTextResponse.copy(block: pl.leancode.automatorserver.contracts.EnterTextResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.EnterTextResponse =
  pl.leancode.automatorserver.contracts.EnterTextResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

