//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializehandlePermissionCommand")
inline fun handlePermissionCommand(block: pl.leancode.automatorserver.contracts.HandlePermissionCommandKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.HandlePermissionCommand =
  pl.leancode.automatorserver.contracts.HandlePermissionCommandKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.HandlePermissionCommand.newBuilder()).apply { block() }._build()
object HandlePermissionCommandKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.HandlePermissionCommand.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.HandlePermissionCommand.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.HandlePermissionCommand = _builder.build()

    /**
     * <code>.patrol.HandlePermissionCommand.Code code = 1;</code>
     */
     var code: pl.leancode.automatorserver.contracts.Contracts.HandlePermissionCommand.Code
      @JvmName("getCode")
      get() = _builder.getCode()
      @JvmName("setCode")
      set(value) {
        _builder.setCode(value)
      }
    /**
     * <code>.patrol.HandlePermissionCommand.Code code = 1;</code>
     */
    fun clearCode() {
      _builder.clearCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.HandlePermissionCommand.copy(block: pl.leancode.automatorserver.contracts.HandlePermissionCommandKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.HandlePermissionCommand =
  pl.leancode.automatorserver.contracts.HandlePermissionCommandKt.Dsl._create(this.toBuilder()).apply { block() }._build()

