//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializenativeWidgetsQuery")
inline fun nativeWidgetsQuery(block: pl.leancode.automatorserver.contracts.NativeWidgetsQueryKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.NativeWidgetsQuery =
  pl.leancode.automatorserver.contracts.NativeWidgetsQueryKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.NativeWidgetsQuery.newBuilder()).apply { block() }._build()
object NativeWidgetsQueryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.NativeWidgetsQuery.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.NativeWidgetsQuery.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.NativeWidgetsQuery = _builder.build()

    /**
     * <code>.patrol.Selector selector = 1;</code>
     */
    var selector: pl.leancode.automatorserver.contracts.Contracts.Selector
      @JvmName("getSelector")
      get() = _builder.getSelector()
      @JvmName("setSelector")
      set(value) {
        _builder.setSelector(value)
      }
    /**
     * <code>.patrol.Selector selector = 1;</code>
     */
    fun clearSelector() {
      _builder.clearSelector()
    }
    /**
     * <code>.patrol.Selector selector = 1;</code>
     * @return Whether the selector field is set.
     */
    fun hasSelector(): kotlin.Boolean {
      return _builder.hasSelector()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.NativeWidgetsQuery.copy(block: pl.leancode.automatorserver.contracts.NativeWidgetsQueryKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.NativeWidgetsQuery =
  pl.leancode.automatorserver.contracts.NativeWidgetsQueryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val pl.leancode.automatorserver.contracts.Contracts.NativeWidgetsQueryOrBuilder.selectorOrNull: pl.leancode.automatorserver.contracts.Contracts.Selector?
  get() = if (hasSelector()) getSelector() else null

