//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializeopenAppCommand")
inline fun openAppCommand(block: pl.leancode.automatorserver.contracts.OpenAppCommandKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.OpenAppCommand =
  pl.leancode.automatorserver.contracts.OpenAppCommandKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.OpenAppCommand.newBuilder()).apply { block() }._build()
object OpenAppCommandKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.OpenAppCommand.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.OpenAppCommand.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.OpenAppCommand = _builder.build()

    /**
     * <code>string appId = 1;</code>
     */
    var appId: kotlin.String
      @JvmName("getAppId")
      get() = _builder.getAppId()
      @JvmName("setAppId")
      set(value) {
        _builder.setAppId(value)
      }
    /**
     * <code>string appId = 1;</code>
     */
    fun clearAppId() {
      _builder.clearAppId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.OpenAppCommand.copy(block: pl.leancode.automatorserver.contracts.OpenAppCommandKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.OpenAppCommand =
  pl.leancode.automatorserver.contracts.OpenAppCommandKt.Dsl._create(this.toBuilder()).apply { block() }._build()

