//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializeopenAppResponse")
inline fun openAppResponse(block: pl.leancode.automatorserver.contracts.OpenAppResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.OpenAppResponse =
  pl.leancode.automatorserver.contracts.OpenAppResponseKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.OpenAppResponse.newBuilder()).apply { block() }._build()
object OpenAppResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.OpenAppResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.OpenAppResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.OpenAppResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.OpenAppResponse.copy(block: pl.leancode.automatorserver.contracts.OpenAppResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.OpenAppResponse =
  pl.leancode.automatorserver.contracts.OpenAppResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

