//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializeopenQuickSettingsRequest")
inline fun openQuickSettingsRequest(block: pl.leancode.automatorserver.contracts.OpenQuickSettingsRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.OpenQuickSettingsRequest =
  pl.leancode.automatorserver.contracts.OpenQuickSettingsRequestKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.OpenQuickSettingsRequest.newBuilder()).apply { block() }._build()
object OpenQuickSettingsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.OpenQuickSettingsRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.OpenQuickSettingsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.OpenQuickSettingsRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.OpenQuickSettingsRequest.copy(block: pl.leancode.automatorserver.contracts.OpenQuickSettingsRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.OpenQuickSettingsRequest =
  pl.leancode.automatorserver.contracts.OpenQuickSettingsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

