//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializeopenNotificationsResponse")
inline fun openNotificationsResponse(block: pl.leancode.automatorserver.contracts.OpenNotificationsResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.OpenNotificationsResponse =
  pl.leancode.automatorserver.contracts.OpenNotificationsResponseKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.OpenNotificationsResponse.newBuilder()).apply { block() }._build()
object OpenNotificationsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.OpenNotificationsResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.OpenNotificationsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.OpenNotificationsResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.OpenNotificationsResponse.copy(block: pl.leancode.automatorserver.contracts.OpenNotificationsResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.OpenNotificationsResponse =
  pl.leancode.automatorserver.contracts.OpenNotificationsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

