//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializepressRecentAppsResponse")
inline fun pressRecentAppsResponse(block: pl.leancode.automatorserver.contracts.PressRecentAppsResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.PressRecentAppsResponse =
  pl.leancode.automatorserver.contracts.PressRecentAppsResponseKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.PressRecentAppsResponse.newBuilder()).apply { block() }._build()
object PressRecentAppsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.PressRecentAppsResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.PressRecentAppsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.PressRecentAppsResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.PressRecentAppsResponse.copy(block: pl.leancode.automatorserver.contracts.PressRecentAppsResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.PressRecentAppsResponse =
  pl.leancode.automatorserver.contracts.PressRecentAppsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

