//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializepressHomeResponse")
inline fun pressHomeResponse(block: pl.leancode.automatorserver.contracts.PressHomeResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.PressHomeResponse =
  pl.leancode.automatorserver.contracts.PressHomeResponseKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.PressHomeResponse.newBuilder()).apply { block() }._build()
object PressHomeResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.PressHomeResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.PressHomeResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.PressHomeResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.PressHomeResponse.copy(block: pl.leancode.automatorserver.contracts.PressHomeResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.PressHomeResponse =
  pl.leancode.automatorserver.contracts.PressHomeResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

