//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializepressBackRequest")
inline fun pressBackRequest(block: pl.leancode.automatorserver.contracts.PressBackRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.PressBackRequest =
  pl.leancode.automatorserver.contracts.PressBackRequestKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.PressBackRequest.newBuilder()).apply { block() }._build()
object PressBackRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.PressBackRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.PressBackRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.PressBackRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.PressBackRequest.copy(block: pl.leancode.automatorserver.contracts.PressBackRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.PressBackRequest =
  pl.leancode.automatorserver.contracts.PressBackRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

