//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializesetLocationAccuracyResponse")
inline fun setLocationAccuracyResponse(block: pl.leancode.automatorserver.contracts.SetLocationAccuracyResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.SetLocationAccuracyResponse =
  pl.leancode.automatorserver.contracts.SetLocationAccuracyResponseKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.SetLocationAccuracyResponse.newBuilder()).apply { block() }._build()
object SetLocationAccuracyResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.SetLocationAccuracyResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.SetLocationAccuracyResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.SetLocationAccuracyResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.SetLocationAccuracyResponse.copy(block: pl.leancode.automatorserver.contracts.SetLocationAccuracyResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.SetLocationAccuracyResponse =
  pl.leancode.automatorserver.contracts.SetLocationAccuracyResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

