//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializeswipeResponse")
inline fun swipeResponse(block: pl.leancode.automatorserver.contracts.SwipeResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.SwipeResponse =
  pl.leancode.automatorserver.contracts.SwipeResponseKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.SwipeResponse.newBuilder()).apply { block() }._build()
object SwipeResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.SwipeResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.SwipeResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.SwipeResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.SwipeResponse.copy(block: pl.leancode.automatorserver.contracts.SwipeResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.SwipeResponse =
  pl.leancode.automatorserver.contracts.SwipeResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

