//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializetapCommand")
inline fun tapCommand(block: pl.leancode.automatorserver.contracts.TapCommandKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.TapCommand =
  pl.leancode.automatorserver.contracts.TapCommandKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.TapCommand.newBuilder()).apply { block() }._build()
object TapCommandKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.TapCommand.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.TapCommand.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.TapCommand = _builder.build()

    /**
     * <code>string appId = 1;</code>
     */
    var appId: kotlin.String
      @JvmName("getAppId")
      get() = _builder.getAppId()
      @JvmName("setAppId")
      set(value) {
        _builder.setAppId(value)
      }
    /**
     * <code>string appId = 1;</code>
     */
    fun clearAppId() {
      _builder.clearAppId()
    }

    /**
     * <code>.patrol.Selector selector = 2;</code>
     */
    var selector: pl.leancode.automatorserver.contracts.Contracts.Selector
      @JvmName("getSelector")
      get() = _builder.getSelector()
      @JvmName("setSelector")
      set(value) {
        _builder.setSelector(value)
      }
    /**
     * <code>.patrol.Selector selector = 2;</code>
     */
    fun clearSelector() {
      _builder.clearSelector()
    }
    /**
     * <code>.patrol.Selector selector = 2;</code>
     * @return Whether the selector field is set.
     */
    fun hasSelector(): kotlin.Boolean {
      return _builder.hasSelector()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.TapCommand.copy(block: pl.leancode.automatorserver.contracts.TapCommandKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.TapCommand =
  pl.leancode.automatorserver.contracts.TapCommandKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val pl.leancode.automatorserver.contracts.Contracts.TapCommandOrBuilder.selectorOrNull: pl.leancode.automatorserver.contracts.Contracts.Selector?
  get() = if (hasSelector()) getSelector() else null

