//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializetapOnNotificationByIndexCommand")
inline fun tapOnNotificationByIndexCommand(block: pl.leancode.automatorserver.contracts.TapOnNotificationByIndexCommandKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.TapOnNotificationByIndexCommand =
  pl.leancode.automatorserver.contracts.TapOnNotificationByIndexCommandKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.TapOnNotificationByIndexCommand.newBuilder()).apply { block() }._build()
object TapOnNotificationByIndexCommandKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.TapOnNotificationByIndexCommand.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.TapOnNotificationByIndexCommand.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.TapOnNotificationByIndexCommand = _builder.build()

    /**
     * <code>uint32 index = 1;</code>
     */
    var index: kotlin.Int
      @JvmName("getIndex")
      get() = _builder.getIndex()
      @JvmName("setIndex")
      set(value) {
        _builder.setIndex(value)
      }
    /**
     * <code>uint32 index = 1;</code>
     */
    fun clearIndex() {
      _builder.clearIndex()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.TapOnNotificationByIndexCommand.copy(block: pl.leancode.automatorserver.contracts.TapOnNotificationByIndexCommandKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.TapOnNotificationByIndexCommand =
  pl.leancode.automatorserver.contracts.TapOnNotificationByIndexCommandKt.Dsl._create(this.toBuilder()).apply { block() }._build()

