//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializetapOnNotificationResponse")
inline fun tapOnNotificationResponse(block: pl.leancode.automatorserver.contracts.TapOnNotificationResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.TapOnNotificationResponse =
  pl.leancode.automatorserver.contracts.TapOnNotificationResponseKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.TapOnNotificationResponse.newBuilder()).apply { block() }._build()
object TapOnNotificationResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.TapOnNotificationResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.TapOnNotificationResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.TapOnNotificationResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.TapOnNotificationResponse.copy(block: pl.leancode.automatorserver.contracts.TapOnNotificationResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.TapOnNotificationResponse =
  pl.leancode.automatorserver.contracts.TapOnNotificationResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

