//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.automatorserver.contracts;

@kotlin.jvm.JvmName("-initializewiFiResponse")
inline fun wiFiResponse(block: pl.leancode.automatorserver.contracts.WiFiResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.WiFiResponse =
  pl.leancode.automatorserver.contracts.WiFiResponseKt.Dsl._create(pl.leancode.automatorserver.contracts.Contracts.WiFiResponse.newBuilder()).apply { block() }._build()
object WiFiResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.automatorserver.contracts.Contracts.WiFiResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.automatorserver.contracts.Contracts.WiFiResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.automatorserver.contracts.Contracts.WiFiResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.automatorserver.contracts.Contracts.WiFiResponse.copy(block: pl.leancode.automatorserver.contracts.WiFiResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.automatorserver.contracts.Contracts.WiFiResponse =
  pl.leancode.automatorserver.contracts.WiFiResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

