name: patrol_next
description: Patrol but with revamped architecture
version: 0.0.1

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  fixnum: ^1.0.1
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  grpc: ^3.0.2
  http: ^0.13.5
  integration_test:
    sdk: flutter
  json_annotation: ^4.6.0
  meta: ^1.7.0
  path: ^1.8.2
  protobuf: ^2.1.0
  vm_service: ^9.0.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  leancode_lint: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: pl.leancode.patrol_next
        pluginClass: PatrolNextPlugin
      ios:
        pluginClass: PatrolNextPlugin
