//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.patrol.contracts;

@kotlin.jvm.JvmName("-initializedarkModeRequest")
public inline fun darkModeRequest(block: pl.leancode.patrol.contracts.DarkModeRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.contracts.Contracts.DarkModeRequest =
  pl.leancode.patrol.contracts.DarkModeRequestKt.Dsl._create(pl.leancode.patrol.contracts.Contracts.DarkModeRequest.newBuilder()).apply { block() }._build()
public object DarkModeRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pl.leancode.patrol.contracts.Contracts.DarkModeRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.patrol.contracts.Contracts.DarkModeRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.patrol.contracts.Contracts.DarkModeRequest = _builder.build()

    /**
     * <code>string appId = 1;</code>
     */
    public var appId: kotlin.String
      @JvmName("getAppId")
      get() = _builder.getAppId()
      @JvmName("setAppId")
      set(value) {
        _builder.setAppId(value)
      }
    /**
     * <code>string appId = 1;</code>
     */
    public fun clearAppId() {
      _builder.clearAppId()
    }
  }
}
public inline fun pl.leancode.patrol.contracts.Contracts.DarkModeRequest.copy(block: pl.leancode.patrol.contracts.DarkModeRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.contracts.Contracts.DarkModeRequest =
  pl.leancode.patrol.contracts.DarkModeRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

