// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package pl.leancode.patrol.contracts;

@kotlin.jvm.JvmName("-initializepermissionDialogVisibleRequest")
public inline fun permissionDialogVisibleRequest(block: pl.leancode.patrol.contracts.PermissionDialogVisibleRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.contracts.Contracts.PermissionDialogVisibleRequest =
  pl.leancode.patrol.contracts.PermissionDialogVisibleRequestKt.Dsl._create(pl.leancode.patrol.contracts.Contracts.PermissionDialogVisibleRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `patrol.PermissionDialogVisibleRequest`
 */
public object PermissionDialogVisibleRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pl.leancode.patrol.contracts.Contracts.PermissionDialogVisibleRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.patrol.contracts.Contracts.PermissionDialogVisibleRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.patrol.contracts.Contracts.PermissionDialogVisibleRequest = _builder.build()

    /**
     * <code>uint64 timeoutMillis = 1;</code>
     */
    public var timeoutMillis: kotlin.Long
      @JvmName("getTimeoutMillis")
      get() = _builder.getTimeoutMillis()
      @JvmName("setTimeoutMillis")
      set(value) {
        _builder.setTimeoutMillis(value)
      }
    /**
     * `uint64 timeoutMillis = 1;`
     */
    public fun clearTimeoutMillis() {
      _builder.clearTimeoutMillis()
    }
  }
}
public inline fun pl.leancode.patrol.contracts.Contracts.PermissionDialogVisibleRequest.copy(block: pl.leancode.patrol.contracts.PermissionDialogVisibleRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.contracts.Contracts.PermissionDialogVisibleRequest =
  pl.leancode.patrol.contracts.PermissionDialogVisibleRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

