//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.patrol.contracts;

@kotlin.jvm.JvmName("-initializerunDartTestResponse")
public inline fun runDartTestResponse(block: pl.leancode.patrol.contracts.RunDartTestResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.contracts.Contracts.RunDartTestResponse =
  pl.leancode.patrol.contracts.RunDartTestResponseKt.Dsl._create(pl.leancode.patrol.contracts.Contracts.RunDartTestResponse.newBuilder()).apply { block() }._build()
public object RunDartTestResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pl.leancode.patrol.contracts.Contracts.RunDartTestResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.patrol.contracts.Contracts.RunDartTestResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.patrol.contracts.Contracts.RunDartTestResponse = _builder.build()

    /**
     * <code>.patrol.RunDartTestResponse.Result result = 1;</code>
     */
    public var result: pl.leancode.patrol.contracts.Contracts.RunDartTestResponse.Result
      @JvmName("getResult")
      get() = _builder.getResult()
      @JvmName("setResult")
      set(value) {
        _builder.setResult(value)
      }
    /**
     * <code>.patrol.RunDartTestResponse.Result result = 1;</code>
     */
    public fun clearResult() {
      _builder.clearResult()
    }
  }
}
public inline fun pl.leancode.patrol.contracts.Contracts.RunDartTestResponse.copy(block: pl.leancode.patrol.contracts.RunDartTestResponseKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.contracts.Contracts.RunDartTestResponse =
  pl.leancode.patrol.contracts.RunDartTestResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

