//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.patrol.contracts;

@kotlin.jvm.JvmName("-initializerunDartTestRequest")
public inline fun runDartTestRequest(block: pl.leancode.patrol.contracts.RunDartTestRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.contracts.Contracts.RunDartTestRequest =
  pl.leancode.patrol.contracts.RunDartTestRequestKt.Dsl._create(pl.leancode.patrol.contracts.Contracts.RunDartTestRequest.newBuilder()).apply { block() }._build()
public object RunDartTestRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pl.leancode.patrol.contracts.Contracts.RunDartTestRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.patrol.contracts.Contracts.RunDartTestRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.patrol.contracts.Contracts.RunDartTestRequest = _builder.build()

    /**
     * <code>string name = 1;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 1;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }
  }
}
public inline fun pl.leancode.patrol.contracts.Contracts.RunDartTestRequest.copy(block: pl.leancode.patrol.contracts.RunDartTestRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.contracts.Contracts.RunDartTestRequest =
  pl.leancode.patrol.contracts.RunDartTestRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

