//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.patrol.contracts;

@kotlin.jvm.JvmName("-initializesetDartTestsRequest")
public inline fun setDartTestsRequest(block: pl.leancode.patrol.contracts.SetDartTestsRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.contracts.Contracts.SetDartTestsRequest =
  pl.leancode.patrol.contracts.SetDartTestsRequestKt.Dsl._create(pl.leancode.patrol.contracts.Contracts.SetDartTestsRequest.newBuilder()).apply { block() }._build()
public object SetDartTestsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: pl.leancode.patrol.contracts.Contracts.SetDartTestsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.patrol.contracts.Contracts.SetDartTestsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.patrol.contracts.Contracts.SetDartTestsRequest = _builder.build()

    /**
     * <code>.patrol.DartTestGroup group = 1;</code>
     */
    public var group: pl.leancode.patrol.contracts.Contracts.DartTestGroup
      @JvmName("getGroup")
      get() = _builder.getGroup()
      @JvmName("setGroup")
      set(value) {
        _builder.setGroup(value)
      }
    /**
     * <code>.patrol.DartTestGroup group = 1;</code>
     */
    public fun clearGroup() {
      _builder.clearGroup()
    }
    /**
     * <code>.patrol.DartTestGroup group = 1;</code>
     * @return Whether the group field is set.
     */
    public fun hasGroup(): kotlin.Boolean {
      return _builder.hasGroup()
    }
  }
}
public inline fun pl.leancode.patrol.contracts.Contracts.SetDartTestsRequest.copy(block: pl.leancode.patrol.contracts.SetDartTestsRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.contracts.Contracts.SetDartTestsRequest =
  pl.leancode.patrol.contracts.SetDartTestsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val pl.leancode.patrol.contracts.Contracts.SetDartTestsRequestOrBuilder.groupOrNull: pl.leancode.patrol.contracts.Contracts.DartTestGroup?
  get() = if (hasGroup()) getGroup() else null

