// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contracts.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DartTestCase;
@class DartTestGroup;
@class NativeView;
@class Notification;
@class Selector;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum RunDartTestResponse_Result

typedef GPB_ENUM(RunDartTestResponse_Result) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  RunDartTestResponse_Result_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  RunDartTestResponse_Result_Success = 0,
  RunDartTestResponse_Result_Skipped = 1,
  RunDartTestResponse_Result_Failure = 2,
};

GPBEnumDescriptor *RunDartTestResponse_Result_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL RunDartTestResponse_Result_IsValidValue(int32_t value);

#pragma mark - Enum HandlePermissionRequest_Code

typedef GPB_ENUM(HandlePermissionRequest_Code) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  HandlePermissionRequest_Code_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  HandlePermissionRequest_Code_WhileUsing = 0,
  HandlePermissionRequest_Code_OnlyThisTime = 1,
  HandlePermissionRequest_Code_Denied = 2,
};

GPBEnumDescriptor *HandlePermissionRequest_Code_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL HandlePermissionRequest_Code_IsValidValue(int32_t value);

#pragma mark - Enum SetLocationAccuracyRequest_LocationAccuracy

typedef GPB_ENUM(SetLocationAccuracyRequest_LocationAccuracy) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  SetLocationAccuracyRequest_LocationAccuracy_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  SetLocationAccuracyRequest_LocationAccuracy_Coarse = 0,
  SetLocationAccuracyRequest_LocationAccuracy_Fine = 1,
};

GPBEnumDescriptor *SetLocationAccuracyRequest_LocationAccuracy_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SetLocationAccuracyRequest_LocationAccuracy_IsValidValue(int32_t value);

#pragma mark - ContractsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ContractsRoot : GPBRootObject
@end

#pragma mark - ListDartTestsResponse

typedef GPB_ENUM(ListDartTestsResponse_FieldNumber) {
  ListDartTestsResponse_FieldNumber_Group = 1,
};

GPB_FINAL @interface ListDartTestsResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) DartTestGroup *group;
/** Test to see if @c group has been set. */
@property(nonatomic, readwrite) BOOL hasGroup;

@end

#pragma mark - DartTestGroup

typedef GPB_ENUM(DartTestGroup_FieldNumber) {
  DartTestGroup_FieldNumber_Name = 1,
  DartTestGroup_FieldNumber_TestsArray = 2,
  DartTestGroup_FieldNumber_GroupsArray = 3,
};

GPB_FINAL @interface DartTestGroup : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DartTestCase*> *testsArray;
/** The number of items in @c testsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger testsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DartTestGroup*> *groupsArray;
/** The number of items in @c groupsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupsArray_Count;

@end

#pragma mark - DartTestCase

typedef GPB_ENUM(DartTestCase_FieldNumber) {
  DartTestCase_FieldNumber_Name = 1,
};

GPB_FINAL @interface DartTestCase : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - RunDartTestRequest

typedef GPB_ENUM(RunDartTestRequest_FieldNumber) {
  RunDartTestRequest_FieldNumber_Name = 1,
};

GPB_FINAL @interface RunDartTestRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - RunDartTestResponse

typedef GPB_ENUM(RunDartTestResponse_FieldNumber) {
  RunDartTestResponse_FieldNumber_Result = 1,
  RunDartTestResponse_FieldNumber_Details = 2,
};

GPB_FINAL @interface RunDartTestResponse : GPBMessage

@property(nonatomic, readwrite) RunDartTestResponse_Result result;

@property(nonatomic, readwrite, copy, null_resettable) NSString *details;
/** Test to see if @c details has been set. */
@property(nonatomic, readwrite) BOOL hasDetails;

@end

/**
 * Fetches the raw value of a @c RunDartTestResponse's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t RunDartTestResponse_Result_RawValue(RunDartTestResponse *message);
/**
 * Sets the raw value of an @c RunDartTestResponse's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRunDartTestResponse_Result_RawValue(RunDartTestResponse *message, int32_t value);

#pragma mark - ConfigureRequest

typedef GPB_ENUM(ConfigureRequest_FieldNumber) {
  ConfigureRequest_FieldNumber_FindTimeoutMillis = 1,
};

GPB_FINAL @interface ConfigureRequest : GPBMessage

@property(nonatomic, readwrite) uint64_t findTimeoutMillis;

@end

#pragma mark - OpenAppRequest

typedef GPB_ENUM(OpenAppRequest_FieldNumber) {
  OpenAppRequest_FieldNumber_AppId = 1,
};

GPB_FINAL @interface OpenAppRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@end

#pragma mark - TapOnNotificationRequest

typedef GPB_ENUM(TapOnNotificationRequest_FieldNumber) {
  TapOnNotificationRequest_FieldNumber_Index = 1,
  TapOnNotificationRequest_FieldNumber_Selector = 2,
};

typedef GPB_ENUM(TapOnNotificationRequest_FindBy_OneOfCase) {
  TapOnNotificationRequest_FindBy_OneOfCase_GPBUnsetOneOfCase = 0,
  TapOnNotificationRequest_FindBy_OneOfCase_Index = 1,
  TapOnNotificationRequest_FindBy_OneOfCase_Selector = 2,
};

GPB_FINAL @interface TapOnNotificationRequest : GPBMessage

@property(nonatomic, readonly) TapOnNotificationRequest_FindBy_OneOfCase findByOneOfCase;

@property(nonatomic, readwrite) uint32_t index;

@property(nonatomic, readwrite, strong, null_resettable) Selector *selector;

@end

/**
 * Clears whatever value was set for the oneof 'findBy'.
 **/
void TapOnNotificationRequest_ClearFindByOneOfCase(TapOnNotificationRequest *message);

#pragma mark - Empty

/**
 * We're defining our own Empty instead of using google.protobuf.Empty because
 * the Dart plugin can't easily generate it.
 *
 * See:
 *  * https://github.com/google/protobuf.dart/issues/170
 **/
GPB_FINAL @interface Empty : GPBMessage

@end

#pragma mark - OpenQuickSettingsRequest

GPB_FINAL @interface OpenQuickSettingsRequest : GPBMessage

@end

#pragma mark - DarkModeRequest

typedef GPB_ENUM(DarkModeRequest_FieldNumber) {
  DarkModeRequest_FieldNumber_AppId = 1,
};

GPB_FINAL @interface DarkModeRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@end

#pragma mark - GetNativeViewsRequest

typedef GPB_ENUM(GetNativeViewsRequest_FieldNumber) {
  GetNativeViewsRequest_FieldNumber_Selector = 1,
  GetNativeViewsRequest_FieldNumber_AppId = 2,
};

GPB_FINAL @interface GetNativeViewsRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Selector *selector;
/** Test to see if @c selector has been set. */
@property(nonatomic, readwrite) BOOL hasSelector;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@end

#pragma mark - GetNativeViewsResponse

typedef GPB_ENUM(GetNativeViewsResponse_FieldNumber) {
  GetNativeViewsResponse_FieldNumber_NativeViewsArray = 2,
};

GPB_FINAL @interface GetNativeViewsResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NativeView*> *nativeViewsArray;
/** The number of items in @c nativeViewsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger nativeViewsArray_Count;

@end

#pragma mark - GetNotificationsRequest

GPB_FINAL @interface GetNotificationsRequest : GPBMessage

@end

#pragma mark - GetNotificationsResponse

typedef GPB_ENUM(GetNotificationsResponse_FieldNumber) {
  GetNotificationsResponse_FieldNumber_NotificationsArray = 2,
};

GPB_FINAL @interface GetNotificationsResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Notification*> *notificationsArray;
/** The number of items in @c notificationsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger notificationsArray_Count;

@end

#pragma mark - TapRequest

typedef GPB_ENUM(TapRequest_FieldNumber) {
  TapRequest_FieldNumber_Selector = 1,
  TapRequest_FieldNumber_AppId = 2,
};

GPB_FINAL @interface TapRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Selector *selector;
/** Test to see if @c selector has been set. */
@property(nonatomic, readwrite) BOOL hasSelector;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@end

#pragma mark - EnterTextRequest

typedef GPB_ENUM(EnterTextRequest_FieldNumber) {
  EnterTextRequest_FieldNumber_Data_p = 1,
  EnterTextRequest_FieldNumber_AppId = 2,
  EnterTextRequest_FieldNumber_Index = 3,
  EnterTextRequest_FieldNumber_Selector = 4,
  EnterTextRequest_FieldNumber_ShowKeyboard = 5,
};

typedef GPB_ENUM(EnterTextRequest_FindBy_OneOfCase) {
  EnterTextRequest_FindBy_OneOfCase_GPBUnsetOneOfCase = 0,
  EnterTextRequest_FindBy_OneOfCase_Index = 3,
  EnterTextRequest_FindBy_OneOfCase_Selector = 4,
};

GPB_FINAL @interface EnterTextRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *data_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@property(nonatomic, readonly) EnterTextRequest_FindBy_OneOfCase findByOneOfCase;

@property(nonatomic, readwrite) uint32_t index;

@property(nonatomic, readwrite, strong, null_resettable) Selector *selector;

@property(nonatomic, readwrite) BOOL showKeyboard;

@end

/**
 * Clears whatever value was set for the oneof 'findBy'.
 **/
void EnterTextRequest_ClearFindByOneOfCase(EnterTextRequest *message);

#pragma mark - SwipeRequest

typedef GPB_ENUM(SwipeRequest_FieldNumber) {
  SwipeRequest_FieldNumber_StartX = 1,
  SwipeRequest_FieldNumber_StartY = 2,
  SwipeRequest_FieldNumber_EndX = 3,
  SwipeRequest_FieldNumber_EndY = 4,
  SwipeRequest_FieldNumber_Steps = 5,
  SwipeRequest_FieldNumber_AppId = 6,
};

GPB_FINAL @interface SwipeRequest : GPBMessage

@property(nonatomic, readwrite) float startX;

@property(nonatomic, readwrite) float startY;

@property(nonatomic, readwrite) float endX;

@property(nonatomic, readwrite) float endY;

@property(nonatomic, readwrite) uint32_t steps;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@end

#pragma mark - WaitUntilVisibleRequest

typedef GPB_ENUM(WaitUntilVisibleRequest_FieldNumber) {
  WaitUntilVisibleRequest_FieldNumber_Selector = 1,
  WaitUntilVisibleRequest_FieldNumber_AppId = 2,
};

GPB_FINAL @interface WaitUntilVisibleRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Selector *selector;
/** Test to see if @c selector has been set. */
@property(nonatomic, readwrite) BOOL hasSelector;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@end

#pragma mark - HandlePermissionRequest

typedef GPB_ENUM(HandlePermissionRequest_FieldNumber) {
  HandlePermissionRequest_FieldNumber_Code = 1,
};

GPB_FINAL @interface HandlePermissionRequest : GPBMessage

@property(nonatomic, readwrite) HandlePermissionRequest_Code code;

@end

/**
 * Fetches the raw value of a @c HandlePermissionRequest's @c code property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t HandlePermissionRequest_Code_RawValue(HandlePermissionRequest *message);
/**
 * Sets the raw value of an @c HandlePermissionRequest's @c code property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetHandlePermissionRequest_Code_RawValue(HandlePermissionRequest *message, int32_t value);

#pragma mark - SetLocationAccuracyRequest

typedef GPB_ENUM(SetLocationAccuracyRequest_FieldNumber) {
  SetLocationAccuracyRequest_FieldNumber_LocationAccuracy = 1,
};

GPB_FINAL @interface SetLocationAccuracyRequest : GPBMessage

@property(nonatomic, readwrite) SetLocationAccuracyRequest_LocationAccuracy locationAccuracy;

@end

/**
 * Fetches the raw value of a @c SetLocationAccuracyRequest's @c locationAccuracy property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t SetLocationAccuracyRequest_LocationAccuracy_RawValue(SetLocationAccuracyRequest *message);
/**
 * Sets the raw value of an @c SetLocationAccuracyRequest's @c locationAccuracy property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSetLocationAccuracyRequest_LocationAccuracy_RawValue(SetLocationAccuracyRequest *message, int32_t value);

#pragma mark - PermissionDialogVisibleRequest

typedef GPB_ENUM(PermissionDialogVisibleRequest_FieldNumber) {
  PermissionDialogVisibleRequest_FieldNumber_TimeoutMillis = 1,
};

GPB_FINAL @interface PermissionDialogVisibleRequest : GPBMessage

@property(nonatomic, readwrite) uint64_t timeoutMillis;

@end

#pragma mark - PermissionDialogVisibleResponse

typedef GPB_ENUM(PermissionDialogVisibleResponse_FieldNumber) {
  PermissionDialogVisibleResponse_FieldNumber_Visible = 1,
};

GPB_FINAL @interface PermissionDialogVisibleResponse : GPBMessage

@property(nonatomic, readwrite) BOOL visible;

@end

#pragma mark - Selector

typedef GPB_ENUM(Selector_FieldNumber) {
  Selector_FieldNumber_Text = 1,
  Selector_FieldNumber_TextStartsWith = 2,
  Selector_FieldNumber_TextContains = 3,
  Selector_FieldNumber_ClassName_p = 4,
  Selector_FieldNumber_ContentDescription = 5,
  Selector_FieldNumber_ContentDescriptionStartsWith = 6,
  Selector_FieldNumber_ContentDescriptionContains = 7,
  Selector_FieldNumber_ResourceId = 8,
  Selector_FieldNumber_Instance = 9,
  Selector_FieldNumber_Enabled = 10,
  Selector_FieldNumber_Focused = 11,
  Selector_FieldNumber_Pkg = 12,
};

GPB_FINAL @interface Selector : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;
/** Test to see if @c text has been set. */
@property(nonatomic, readwrite) BOOL hasText;

@property(nonatomic, readwrite, copy, null_resettable) NSString *textStartsWith;
/** Test to see if @c textStartsWith has been set. */
@property(nonatomic, readwrite) BOOL hasTextStartsWith;

@property(nonatomic, readwrite, copy, null_resettable) NSString *textContains;
/** Test to see if @c textContains has been set. */
@property(nonatomic, readwrite) BOOL hasTextContains;

@property(nonatomic, readwrite, copy, null_resettable) NSString *className_p;
/** Test to see if @c className_p has been set. */
@property(nonatomic, readwrite) BOOL hasClassName_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *contentDescription;
/** Test to see if @c contentDescription has been set. */
@property(nonatomic, readwrite) BOOL hasContentDescription;

@property(nonatomic, readwrite, copy, null_resettable) NSString *contentDescriptionStartsWith;
/** Test to see if @c contentDescriptionStartsWith has been set. */
@property(nonatomic, readwrite) BOOL hasContentDescriptionStartsWith;

@property(nonatomic, readwrite, copy, null_resettable) NSString *contentDescriptionContains;
/** Test to see if @c contentDescriptionContains has been set. */
@property(nonatomic, readwrite) BOOL hasContentDescriptionContains;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resourceId;
/** Test to see if @c resourceId has been set. */
@property(nonatomic, readwrite) BOOL hasResourceId;

@property(nonatomic, readwrite) uint32_t instance;

@property(nonatomic, readwrite) BOOL hasInstance;
@property(nonatomic, readwrite) BOOL enabled;

@property(nonatomic, readwrite) BOOL hasEnabled;
@property(nonatomic, readwrite) BOOL focused;

@property(nonatomic, readwrite) BOOL hasFocused;
@property(nonatomic, readwrite, copy, null_resettable) NSString *pkg;
/** Test to see if @c pkg has been set. */
@property(nonatomic, readwrite) BOOL hasPkg;

@end

#pragma mark - NativeView

typedef GPB_ENUM(NativeView_FieldNumber) {
  NativeView_FieldNumber_ClassName_p = 1,
  NativeView_FieldNumber_Text = 2,
  NativeView_FieldNumber_ContentDescription = 3,
  NativeView_FieldNumber_Focused = 4,
  NativeView_FieldNumber_Enabled = 5,
  NativeView_FieldNumber_ChildCount = 6,
  NativeView_FieldNumber_ResourceName = 7,
  NativeView_FieldNumber_ApplicationPackage = 8,
  NativeView_FieldNumber_ChildrenArray = 9,
};

/**
 * Represents a native UI control.
 *
 * On Android, this is `android.view.View`.
 **/
GPB_FINAL @interface NativeView : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *className_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

@property(nonatomic, readwrite, copy, null_resettable) NSString *contentDescription;

@property(nonatomic, readwrite) BOOL focused;

@property(nonatomic, readwrite) BOOL enabled;

@property(nonatomic, readwrite) int32_t childCount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resourceName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *applicationPackage;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NativeView*> *childrenArray;
/** The number of items in @c childrenArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger childrenArray_Count;

@end

#pragma mark - Notification

typedef GPB_ENUM(Notification_FieldNumber) {
  Notification_FieldNumber_AppName = 1,
  Notification_FieldNumber_Title = 2,
  Notification_FieldNumber_Content = 3,
  Notification_FieldNumber_Raw = 4,
};

/**
 * Represents a notification visible in the notification shade.
 **/
GPB_FINAL @interface Notification : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appName;
/** Test to see if @c appName has been set. */
@property(nonatomic, readwrite) BOOL hasAppName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *raw;

@end

#pragma mark - SubmitTestResultsRequest

typedef GPB_ENUM(SubmitTestResultsRequest_FieldNumber) {
  SubmitTestResultsRequest_FieldNumber_Results = 1,
};

GPB_FINAL @interface SubmitTestResultsRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *results;
/** The number of items in @c results without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger results_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
