name: windows_poc
description: Patrol Windows capability demo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  patrol:
    path: ../../../packages/patrol

flutter:
  uses-material-design: true
