default_platform(:ios)

platform :ios do
  desc "Build automation server artifacts"
  lane :build do
    run_tests(
      project: "AutomatorServer.xcodeproj",
      scheme: "AutomatorServer",
      derived_data_path: "./derived_data",
      build_for_testing: true,
      sdk: "iphonesimulator"
    )

    derived_data/Build/Products/Debug-iphonesimulator/AutomatorServerUITests-Runner.app
  end
end
