//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: contracts.proto

package pl.leancode.patrol.example.contracts;

@kotlin.jvm.JvmName("-initializeconfigureRequest")
inline fun configureRequest(block: pl.leancode.patrol.example.contracts.ConfigureRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.example.contracts.Contracts.ConfigureRequest =
  pl.leancode.patrol.example.contracts.ConfigureRequestKt.Dsl._create(pl.leancode.patrol.example.contracts.Contracts.ConfigureRequest.newBuilder()).apply { block() }._build()
object ConfigureRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: pl.leancode.patrol.example.contracts.Contracts.ConfigureRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: pl.leancode.patrol.example.contracts.Contracts.ConfigureRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): pl.leancode.patrol.example.contracts.Contracts.ConfigureRequest = _builder.build()

    /**
     * <code>uint64 findTimeoutMillis = 1;</code>
     */
    var findTimeoutMillis: kotlin.Long
      @JvmName("getFindTimeoutMillis")
      get() = _builder.getFindTimeoutMillis()
      @JvmName("setFindTimeoutMillis")
      set(value) {
        _builder.setFindTimeoutMillis(value)
      }
    /**
     * <code>uint64 findTimeoutMillis = 1;</code>
     */
    fun clearFindTimeoutMillis() {
      _builder.clearFindTimeoutMillis()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun pl.leancode.patrol.example.contracts.Contracts.ConfigureRequest.copy(block: pl.leancode.patrol.example.contracts.ConfigureRequestKt.Dsl.() -> kotlin.Unit): pl.leancode.patrol.example.contracts.Contracts.ConfigureRequest =
  pl.leancode.patrol.example.contracts.ConfigureRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
