name: adb publish

on:
  push:
    tags: ['adb-v*']

jobs:
  main:
    name: Publish on pub.dev
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    defaults:
      run:
        working-directory: packages/adb

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - uses: leancodepl/mobile-tools/.github/actions/pub-release@v1
