name: patrol check semver

on:
  workflow_dispatch:
  pull_request:

jobs:
  check_gen_from_schema:
    name: Check gen from schema
    runs-on: ubuntu-latest

    steps:
        - name: Clone repository
          uses: actions/checkout@v4
  
        - name: Check if files are up to date
          run: |
            git diff --quiet master -- schema.dart || {
              echo "schema.dart has changed. Please run gen_from_schema to update the generated files."
              exit 1
            }
