name: patrol_devtools_extension prepare

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/patrol_devtools_extension/**'

jobs:
  prepare:
    name: Flutter ${{ matrix.flutter-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        flutter-version: ['3.16.x']
        flutter-channel: ['stable']

    defaults:
      run:
        working-directory: packages/patrol_devtools_extension

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: ${{ matrix.flutter-channel }}

      - name: flutter pub get
        run: flutter pub get

      - name: flutter test
        if: success() || failure()
        run: flutter test

      - name: Run analyzer
        if: success() || failure()
        run: |
          flutter analyze
          dart run custom_lint

      - name: dart format
        if: success() || failure()
        run: dart format --set-exit-if-changed .

      - name: Build extension
        if: success() || failure()
        run: ./publish_to_patrol_extension
