name: patrol_log check semver

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/patrol_log/**'

jobs:
  check_semver:
    name: Check semver
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        flutter-version: ['3.24.x']
        flutter-channel: ['stable']

    steps:
        - name: Clone repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
  
        - name: Get last released version
          id: get_last_released_version
          run: |
            last_version=$(git tag --list 'patrol_log-v*' | grep -v '\-dev\.[0-9]\+$' | sort -V | tail -n 1 | sed 's/^patrol_log-v//')
            echo "last_version=$last_version" >> $GITHUB_ENV
            echo "::set-output name=last_version::$last_version"

        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: ${{ matrix.flutter-version }}
            channel: ${{ matrix.flutter-channel }}

        - name: Install dart-apitool
          run: dart pub global activate dart_apitool 0.19.0

        - name: Check API changes
          run: |
            dart-apitool diff \
            --old pub://patrol_log/${{ steps.get_last_released_version.outputs.last_version }} \
            --new packages/patrol_log
