name: test locales on android device

on:
  workflow_dispatch:
  schedule:
    # run this workflow every 12 hours
    - cron: '0 */12 * * *'

jobs:
  run_tests:
    name: Flutter ${{ matrix.flutter-version }} on API ${{ matrix.api-level }} (${{ matrix.locale }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      SLACK_MESSAGE_TITLE: Flutter ${{ matrix.flutter-version }} on API ${{ matrix.api-level }} (${{ matrix.locale }})
      TESTS_EXIT_CODE: ${{ steps.tests_step.outputs.TESTS_EXIT_CODE }}
      URL_TO_DETAILS: ${{ steps.tests_step.outputs.URL_TO_DETAILS }}

    strategy:
      fail-fast: false
      matrix:
        flutter-version: ['3.38.x']
        flutter-channel: ['stable']
        locale: ['en_US', 'fr_FR', 'de_DE', 'pl_PL']
        device-model: ['Pixel7']
        api-level: ['36']

    defaults:
      run:
        working-directory: dev/e2e_app

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          generate-job-summary: false

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: ${{ matrix.flutter-channel }}

      - name: Preload Flutter artifacts
        run: flutter precache --android

      - name: Set up Melos and activate workspace
        working-directory: .
        run: |
          dart pub global activate melos
          melos bootstrap

      - name: Set up Patrol CLI
        working-directory: packages/patrol_cli
        run: dart pub global activate --source path . && patrol

      - name: Generate Gradle wrapper
        run: flutter build apk --config-only

      - name: Install ew-cli
        run: |
          mkdir -p "$HOME/bin"
          curl "https://maven.emulator.wtf/releases/ew-cli" -o "$HOME/bin/ew-cli"
          chmod a+x "$HOME/bin/ew-cli"
          echo "$HOME/bin" >> $GITHUB_PATH
          echo "EW_API_TOKEN=${{ secrets.EW_API_TOKEN }}" >> $GITHUB_ENV

      - name: patrol build android
        run: |
          patrol build android --tags locale_testing_android --exclude patrol_test/web/,patrol_test/native_tests/,patrol_test/volume_test.dart --verbose

      - name: Upload APKs to emulator.wtf and wait for tests to finish
        id: tests_step
        run: |
          set +e
          output="$(ew-cli emulatorwtf.yaml:multi_api \
            --device '[model=${{ matrix.device-model }},version=${{ matrix.api-level }},locale=${{ matrix.locale }}]' \
            --display-name "Patrol locale tests API ${{ matrix.api-level }} (${{ matrix.locale }}) (${GITHUB_SHA::7})")"
          TESTS_EXIT_CODE=$?
          set -e

          # Extract the results URL and write it to GitHub summary
          link="$(echo "$output" | jq -r ".resultsUrl")"
          echo "[Test details on emulator.wtf]($link) (LeanCode members only)" >> "$GITHUB_STEP_SUMMARY"

          echo "URL_TO_DETAILS=$link" >> "$GITHUB_OUTPUT"
          echo "TESTS_EXIT_CODE=$TESTS_EXIT_CODE" >> "$GITHUB_OUTPUT"
          exit $TESTS_EXIT_CODE

  call_send_slack_message:
    name: Notify on Slack
    uses: ./.github/workflows/send-slack-message.yaml
    needs: run_tests
    if: always()
    with:
      TESTS_EXIT_CODE: ${{ needs.run_tests.outputs.TESTS_EXIT_CODE }}
      SLACK_MESSAGE_TITLE: ${{ needs.run_tests.outputs.SLACK_MESSAGE_TITLE }}
      URL_TO_DETAILS: ${{ needs.run_tests.outputs.URL_TO_DETAILS }}
    secrets: inherit
