name: testlab ios

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  main:
    name: "Test on iOS on Firebase Test Lab"
    runs-on: macos-latest
    timeout-minutes: 60

    defaults:
      run:
        working-directory: packages/patrol/example

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_JSON }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          generate-job-summary: false

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter-channel }}

      - name: Preload Flutter artifacts
        run: flutter precache

      - name: "Configure Flutter build options"
        run: flutter build ios --target integration_test/example_test.dart" --release

      - name: "Build app and create zip archive"
        run: |
          cd ios
          xcodebuild build-for-testing \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -xcconfig Flutter/Release.xcconfig \
            -configuration Release \
            -derivedDataPath ../build/ios_integ \
            -sdk iphoneos

          zip -r "ios_tests.zip" Release-iphoneos Runner_iphoneos*

      - name: "Upload and test on Firebase Test Lab"
        run: |
          gcloud firebase test ios run \
            --test "build/ios_integ/Build/Products/ios_tests.zip" \
            --device model=iphone8,version="$dev_target",locale=en_US,orientation=portrait
