import 'package:file/file.dart';
import 'package:patrol_cli/src/crossplatform/test_manifest.dart';

/// Generates a static Objective-C XCTest source file from a build-time test
/// manifest, so each Dart test becomes a real native test method.
///
/// This replaces the runtime `+testInvocations` discovery (launch the app, ask
/// over HTTP, `class_addMethod`) with compiled methods that XCTest discovers
/// natively - enabling the Xcode test navigator, test plans and per-test
/// `-only-testing` sharding.
///
/// One XCTestCase subclass is generated per Dart test file, all inheriting the
/// shared infrastructure from the base class opened by
/// `PATROL_INTEGRATION_TEST_IOS_RUNNER_STATIC_BASE`, so reports group by file
/// and a whole file is selectable with one `-only-testing` value. Class and
/// method names come from [generatePerFileTestNames], the same source the
/// Android codegen uses, so both platforms report the same names.
///
/// Selectors are sanitized identifiers (Dart names contain spaces, quotes and
/// unicode and cannot be Objective-C selectors); the original Dart test name is
/// embedded in the method body and handed to `runDartTest`, so the names the app
/// receives stay byte-identical to runtime discovery.
class XcodeTestCodegen {
  XcodeTestCodegen(this._fs);

  final FileSystem _fs;

  /// Reads the manifest JSON at [manifestPath] and writes the generated
  /// Objective-C category to [outputPath]. Returns the number of generated
  /// test methods.
  int generate({
    required String manifestPath,
    required String outputPath,
    String className = 'RunnerUITests',
  }) {
    final tests = TestManifest.parse(
      _fs.file(manifestPath).readAsStringSync(),
    ).tests;

    final source = _render(className, tests);
    _fs.file(outputPath)
      ..createSync(recursive: true)
      ..writeAsStringSync(source);
    return tests.length;
  }

  String _render(String className, List<DiscoveredTest> tests) {
    final names = generatePerFileTestNames(tests);
    // This file is #included after the base class, so it declares the test
    // classes itself; it must not carry its own @import wrapper.
    final buffer = StringBuffer()
      ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
      ..writeln(
        '// Generated by `patrol build ios` from the build-time test manifest.',
      )
      ..writeln(
        '// #included after @implementation $className (see RunnerUITests.m).',
      )
      ..writeln();

    final byClass = <String, List<int>>{};
    for (var i = 0; i < tests.length; i++) {
      byClass.putIfAbsent(names[i].className, () => <int>[]).add(i);
    }

    for (final entry in byClass.entries) {
      buffer
        ..writeln('@interface ${entry.key} : $className')
        ..writeln('@end')
        ..writeln()
        ..writeln('@implementation ${entry.key}')
        ..writeln();
      for (final i in entry.value) {
        final literal = _objcStringLiteral(tests[i].dartName);
        buffer
          ..writeln('- (void)${names[i].methodName} {')
          ..writeln(
            '  [self patrolExecuteDartTest:$literal skip:${tests[i].skip ? 'YES' : 'NO'}];',
          )
          ..writeln('}')
          ..writeln();
      }
      buffer
        ..writeln('@end')
        ..writeln();
    }

    return buffer.toString();
  }

  String _objcStringLiteral(String value) {
    final escaped = value
        .replaceAll(r'\', r'\\')
        .replaceAll('"', r'\"')
        .replaceAll('\n', r'\n')
        .replaceAll('\r', r'\r')
        .replaceAll('\t', r'\t');
    return '@"$escaped"';
  }
}
