import 'package:file/file.dart';
import 'package:patrol_cli/src/crossplatform/test_manifest.dart';

/// Generates a static Objective-C XCTest source file from a build-time test
/// manifest, so each Dart test becomes a real native test method.
///
/// This replaces the runtime `+testInvocations` discovery (launch the app, ask
/// over HTTP, `class_addMethod`) with compiled methods that XCTest discovers
/// natively - enabling the Xcode test navigator, test plans and per-test
/// `-only-testing` sharding.
///
/// The selector is a sanitized, unique identifier (Dart names contain spaces,
/// quotes and unicode and cannot be Objective-C selectors); the original Dart
/// test name is embedded in the method body and handed to `runDartTest`, so the
/// names stay byte-identical to runtime discovery.
class XcodeTestCodegen {
  XcodeTestCodegen(this._fs);

  final FileSystem _fs;

  /// Reads the manifest JSON at [manifestPath] and writes the generated
  /// Objective-C category to [outputPath]. Returns the number of generated
  /// test methods.
  int generate({
    required String manifestPath,
    required String outputPath,
    String className = 'RunnerUITests',
  }) {
    final tests = TestManifest.parse(
      _fs.file(manifestPath).readAsStringSync(),
    ).tests;

    final source = _render(className, tests);
    _fs.file(outputPath)
      ..createSync(recursive: true)
      ..writeAsStringSync(source);
    return tests.length;
  }

  String _render(String className, List<DiscoveredTest> tests) {
    final selectors = generateIosSelectors(tests);
    // Methods only: this file is #included inside the `@implementation` opened
    // by PATROL_INTEGRATION_TEST_IOS_RUNNER_STATIC_BEGIN, so it must not carry
    // its own @import/@interface/@implementation wrapper.
    final buffer = StringBuffer()
      ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
      ..writeln('// Generated by `patrol build ios` from the build-time test manifest.')
      ..writeln('// #included inside @implementation $className (see RunnerUITests.m).')
      ..writeln();

    for (var i = 0; i < tests.length; i++) {
      final test = tests[i];
      final selector = selectors[i];
      final literal = _objcStringLiteral(test.dartName);
      buffer
        ..writeln('- (void)$selector {')
        ..writeln(
          '  [self patrolExecuteDartTest:$literal skip:${test.skip ? 'YES' : 'NO'}];',
        )
        ..writeln('}')
        ..writeln();
    }

    return buffer.toString();
  }

  String _objcStringLiteral(String value) {
    final escaped = value
        .replaceAll(r'\', r'\\')
        .replaceAll('"', r'\"')
        .replaceAll('\n', r'\n');
    return '@"$escaped"';
  }
}
