import 'dart:convert';

import 'package:file/file.dart';

/// A single discovered Dart test, flattened to the name the native runner uses.
class _FlatTest {
  _FlatTest(this.dartName, this.skip);
  final String dartName;
  final bool skip;
}

/// Generates a static Objective-C XCTest source file from a build-time test
/// manifest, so each Dart test becomes a real native test method.
///
/// This replaces the runtime `+testInvocations` discovery (launch the app, ask
/// over HTTP, `class_addMethod`) with compiled methods that XCTest discovers
/// natively - enabling the Xcode test navigator, test plans and per-test
/// `-only-testing` sharding.
///
/// The selector is a sanitized, unique identifier (Dart names contain spaces,
/// quotes and unicode and cannot be Objective-C selectors); the original Dart
/// test name is embedded in the method body and handed to `runDartTest`, so the
/// names stay byte-identical to runtime discovery.
class XcodeTestCodegen {
  XcodeTestCodegen(this._fs);

  final FileSystem _fs;

  /// Reads the manifest JSON at [manifestPath] and writes the generated
  /// Objective-C category to [outputPath]. Returns the number of generated
  /// test methods.
  int generate({
    required String manifestPath,
    required String outputPath,
    String className = 'RunnerUITests',
  }) {
    final json =
        jsonDecode(_fs.file(manifestPath).readAsStringSync())
            as Map<String, dynamic>;
    final tree = json['group'] as Map<String, dynamic>;

    final tests = <_FlatTest>[];
    _flatten(tree, '', tests);

    final source = _render(className, tests);
    _fs.file(outputPath)
      ..createSync(recursive: true)
      ..writeAsStringSync(source);
    return tests.length;
  }

  /// Flattens the group tree the exact same way as Swift `listTestsFlat`:
  /// group names joined with spaces, top-level groups not prefixed.
  void _flatten(
    Map<String, dynamic> group,
    String parentGroupName,
    List<_FlatTest> out,
  ) {
    final entries = (group['entries'] as List).cast<Map<String, dynamic>>();
    for (final entry in entries) {
      final name = entry['name'] as String;
      if (entry['type'] == 'test') {
        out.add(_FlatTest('$parentGroupName $name', entry['skip'] as bool));
      } else {
        final childParent = parentGroupName.isEmpty
            ? name
            : '$parentGroupName $name';
        _flatten(entry, childParent, out);
      }
    }
  }

  String _render(String className, List<_FlatTest> tests) {
    final usedSelectors = <String>{};
    // Methods only: this file is #included inside the `@implementation` opened
    // by PATROL_INTEGRATION_TEST_IOS_RUNNER_STATIC_BEGIN, so it must not carry
    // its own @import/@interface/@implementation wrapper.
    final buffer = StringBuffer()
      ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
      ..writeln('// Generated by `patrol build ios` from the build-time test manifest.')
      ..writeln('// #included inside @implementation $className (see RunnerUITests.m).')
      ..writeln();

    for (var i = 0; i < tests.length; i++) {
      final test = tests[i];
      final selector = _uniqueSelector(test.dartName, i, usedSelectors);
      final literal = _objcStringLiteral(test.dartName);
      buffer
        ..writeln('- (void)$selector {')
        ..writeln(
          '  [self patrolExecuteDartTest:$literal skip:${test.skip ? 'YES' : 'NO'}];',
        )
        ..writeln('}')
        ..writeln();
    }

    return buffer.toString();
  }

  String _uniqueSelector(String dartName, int index, Set<String> used) {
    var sanitized = dartName
        .replaceAll(RegExp('[^A-Za-z0-9]+'), '_')
        .replaceAll(RegExp('_+'), '_')
        .replaceAll(RegExp(r'^_|_$'), '');
    // Keep selectors readable but bounded.
    if (sanitized.length > 80) {
      sanitized = sanitized.substring(0, 80);
    }
    // Index guarantees uniqueness and stable ordering even when two Dart names
    // sanitize to the same identifier (e.g. differ only by punctuation).
    final base = 'test_${sanitized}_${index.toString().padLeft(4, '0')}';
    // The index already makes this unique; the suffix is purely defensive.
    var selector = base;
    var dedup = 0;
    while (used.contains(selector)) {
      dedup++;
      selector = '${base}_$dedup';
    }
    used.add(selector);
    return selector;
  }

  String _objcStringLiteral(String value) {
    final escaped = value
        .replaceAll(r'\', r'\\')
        .replaceAll('"', r'\"')
        .replaceAll('\n', r'\n');
    return '@"$escaped"';
  }
}
